//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： lxj1987
//             Created Time： 2016/6/30 19:08:08
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class ST_PROTYPEEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>CODE</summary>
        public const string @__CODE = "CODE";
        
        /// <summary>VVALUE</summary>
        public const string @__VVALUE = "VVALUE";
        
        /// <summary>IORDER</summary>
        public const string @__IORDER = "IORDER";
        
        private decimal m_ID;
        
        private string m_CODE;
        
        private string m_VVALUE;
        
        private decimal m_IORDER;
        
        /// <summary>构造函数</summary>
        public ST_PROTYPEEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性CODE </summary>
        public string CODE
        {
            get
            {
                return this.m_CODE;
            }
            set
            {
                this.m_CODE = value;
            }
        }
        
        /// <summary>属性VVALUE </summary>
        public string VVALUE
        {
            get
            {
                return this.m_VVALUE;
            }
            set
            {
                this.m_VVALUE = value;
            }
        }
        
        /// <summary>属性IORDER </summary>
        public decimal IORDER
        {
            get
            {
                return this.m_IORDER;
            }
            set
            {
                this.m_IORDER = value;
            }
        }
    }
    
    /// ST_PROTYPEEntity执行类
    public abstract class ST_PROTYPEEntityAction
    {
        
        private ST_PROTYPEEntityAction()
        {
        }
        
        public static void Save(ST_PROTYPEEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static ST_PROTYPEEntity RetrieveAST_PROTYPEEntity(decimal ID)
        {
            ST_PROTYPEEntity obj=new ST_PROTYPEEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveST_PROTYPEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(ST_PROTYPEEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetST_PROTYPEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(ST_PROTYPEEntity));
            return rc.AsDataTable();
        }
    }
}
