//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/11 13:54:26
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class SYS_BASE_USERSEntity : EntityObject
    {
        
        /// <summary>NB_ID</summary>
        public const string @__NB_ID = "NB_ID";
        
        /// <summary>VAR_NICK_NAME</summary>
        public const string @__VAR_NICK_NAME = "VAR_NICK_NAME";
        
        /// <summary>VAR_ZH</summary>
        public const string @__VAR_ZH = "VAR_ZH";
        
        /// <summary>VAR_PHONE</summary>
        public const string @__VAR_PHONE = "VAR_PHONE";
        
        /// <summary>VAR_MM</summary>
        public const string @__VAR_MM = "VAR_MM";
        
        /// <summary>VAR_SEX</summary>
        public const string @__VAR_SEX = "VAR_SEX";
        
        /// <summary>VAR_REAL_NAME</summary>
        public const string @__VAR_REAL_NAME = "VAR_REAL_NAME";
        
        /// <summary>VAR_OTHERPHONE</summary>
        public const string @__VAR_OTHERPHONE = "VAR_OTHERPHONE";
        
        /// <summary>VAR_ICARD</summary>
        public const string @__VAR_ICARD = "VAR_ICARD";
        
        /// <summary>NB_LY</summary>
        public const string @__NB_LY = "NB_LY";
        
        /// <summary>VAR_HEADURL</summary>
        public const string @__VAR_HEADURL = "VAR_HEADURL";
        
        /// <summary>DT_ADD_TIME</summary>
        public const string @__DT_ADD_TIME = "DT_ADD_TIME";
        
        /// <summary>VAR_ADD_REMARK</summary>
        public const string @__VAR_ADD_REMARK = "VAR_ADD_REMARK";
        
        /// <summary>NB_ZT</summary>
        public const string @__NB_ZT = "NB_ZT";
        
        private decimal m_NB_ID;
        
        private string m_VAR_NICK_NAME;
        
        private string m_VAR_ZH;
        
        private string m_VAR_PHONE;
        
        private string m_VAR_MM;
        
        private string m_VAR_SEX;
        
        private string m_VAR_REAL_NAME;
        
        private string m_VAR_OTHERPHONE;
        
        private string m_VAR_ICARD;
        
        private decimal m_NB_LY;
        
        private string m_VAR_HEADURL;
        
        private System.DateTime m_DT_ADD_TIME = DateTime.MinValue;
        
        private string m_VAR_ADD_REMARK;
        
        private decimal m_NB_ZT;
        
        /// <summary>构造函数</summary>
        public SYS_BASE_USERSEntity()
        {
        }
        
        /// <summary>属性NB_ID </summary>
        public decimal NB_ID
        {
            get
            {
                return this.m_NB_ID;
            }
            set
            {
                this.m_NB_ID = value;
            }
        }
        
        /// <summary>属性VAR_NICK_NAME </summary>
        public string VAR_NICK_NAME
        {
            get
            {
                return this.m_VAR_NICK_NAME;
            }
            set
            {
                this.m_VAR_NICK_NAME = value;
            }
        }
        
        /// <summary>属性VAR_ZH </summary>
        public string VAR_ZH
        {
            get
            {
                return this.m_VAR_ZH;
            }
            set
            {
                this.m_VAR_ZH = value;
            }
        }
        
        /// <summary>属性VAR_PHONE </summary>
        public string VAR_PHONE
        {
            get
            {
                return this.m_VAR_PHONE;
            }
            set
            {
                this.m_VAR_PHONE = value;
            }
        }
        
        /// <summary>属性VAR_MM </summary>
        public string VAR_MM
        {
            get
            {
                return this.m_VAR_MM;
            }
            set
            {
                this.m_VAR_MM = value;
            }
        }
        
        /// <summary>属性VAR_SEX </summary>
        public string VAR_SEX
        {
            get
            {
                return this.m_VAR_SEX;
            }
            set
            {
                this.m_VAR_SEX = value;
            }
        }
        
        /// <summary>属性VAR_REAL_NAME </summary>
        public string VAR_REAL_NAME
        {
            get
            {
                return this.m_VAR_REAL_NAME;
            }
            set
            {
                this.m_VAR_REAL_NAME = value;
            }
        }
        
        /// <summary>属性VAR_OTHERPHONE </summary>
        public string VAR_OTHERPHONE
        {
            get
            {
                return this.m_VAR_OTHERPHONE;
            }
            set
            {
                this.m_VAR_OTHERPHONE = value;
            }
        }
        
        /// <summary>属性VAR_ICARD </summary>
        public string VAR_ICARD
        {
            get
            {
                return this.m_VAR_ICARD;
            }
            set
            {
                this.m_VAR_ICARD = value;
            }
        }
        
        /// <summary>属性NB_LY </summary>
        public decimal NB_LY
        {
            get
            {
                return this.m_NB_LY;
            }
            set
            {
                this.m_NB_LY = value;
            }
        }
        
        /// <summary>属性VAR_HEADURL </summary>
        public string VAR_HEADURL
        {
            get
            {
                return this.m_VAR_HEADURL;
            }
            set
            {
                this.m_VAR_HEADURL = value;
            }
        }
        
        /// <summary>属性DT_ADD_TIME </summary>
        public System.DateTime DT_ADD_TIME
        {
            get
            {
                return this.m_DT_ADD_TIME;
            }
            set
            {
                this.m_DT_ADD_TIME = value;
            }
        }
        
        /// <summary>属性VAR_ADD_REMARK </summary>
        public string VAR_ADD_REMARK
        {
            get
            {
                return this.m_VAR_ADD_REMARK;
            }
            set
            {
                this.m_VAR_ADD_REMARK = value;
            }
        }
        
        /// <summary>属性NB_ZT </summary>
        public decimal NB_ZT
        {
            get
            {
                return this.m_NB_ZT;
            }
            set
            {
                this.m_NB_ZT = value;
            }
        }
    }
    
    /// SYS_BASE_USERSEntity执行类
    public abstract class SYS_BASE_USERSEntityAction
    {
        
        private SYS_BASE_USERSEntityAction()
        {
        }
        
        public static void Save(SYS_BASE_USERSEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static SYS_BASE_USERSEntity RetrieveASYS_BASE_USERSEntity(decimal NB_ID)
        {
            SYS_BASE_USERSEntity obj=new SYS_BASE_USERSEntity();
            obj.NB_ID=NB_ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveSYS_BASE_USERSEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(SYS_BASE_USERSEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetSYS_BASE_USERSEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(SYS_BASE_USERSEntity));
            return rc.AsDataTable();
        }
    }
}
