//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/30 20:29:28
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_BLINDSIGNEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>MEMBERID</summary>
        public const string @__MEMBERID = "MEMBERID";
        
        /// <summary>ACTIVITYID</summary>
        public const string @__ACTIVITYID = "ACTIVITYID";
        
        /// <summary>LINKNAME</summary>
        public const string @__LINKNAME = "LINKNAME";
        
        /// <summary>TELEPHONE</summary>
        public const string @__TELEPHONE = "TELEPHONE";
        
        /// <summary>STATUS</summary>
        public const string @__STATUS = "STATUS";
        
        /// <summary>USERNMAE</summary>
        public const string @__USERNMAE = "USERNMAE";
        
        /// <summary>CHECKTIME</summary>
        public const string @__CHECKTIME = "CHECKTIME";
        
        private decimal m_ID;
        
        private decimal m_MEMBERID;
        
        private decimal m_ACTIVITYID;
        
        private string m_LINKNAME;
        
        private string m_TELEPHONE;
        
        private decimal m_STATUS;
        
        private string m_USERNMAE;
        
        private System.DateTime m_CHECKTIME = DateTime.MinValue;
        
        /// <summary>构造函数</summary>
        public T_BLINDSIGNEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性MEMBERID </summary>
        public decimal MEMBERID
        {
            get
            {
                return this.m_MEMBERID;
            }
            set
            {
                this.m_MEMBERID = value;
            }
        }
        
        /// <summary>属性ACTIVITYID </summary>
        public decimal ACTIVITYID
        {
            get
            {
                return this.m_ACTIVITYID;
            }
            set
            {
                this.m_ACTIVITYID = value;
            }
        }
        
        /// <summary>属性LINKNAME </summary>
        public string LINKNAME
        {
            get
            {
                return this.m_LINKNAME;
            }
            set
            {
                this.m_LINKNAME = value;
            }
        }
        
        /// <summary>属性TELEPHONE </summary>
        public string TELEPHONE
        {
            get
            {
                return this.m_TELEPHONE;
            }
            set
            {
                this.m_TELEPHONE = value;
            }
        }
        
        /// <summary>属性STATUS </summary>
        public decimal STATUS
        {
            get
            {
                return this.m_STATUS;
            }
            set
            {
                this.m_STATUS = value;
            }
        }
        
        /// <summary>属性USERNMAE </summary>
        public string USERNMAE
        {
            get
            {
                return this.m_USERNMAE;
            }
            set
            {
                this.m_USERNMAE = value;
            }
        }
        
        /// <summary>属性CHECKTIME </summary>
        public System.DateTime CHECKTIME
        {
            get
            {
                return this.m_CHECKTIME;
            }
            set
            {
                this.m_CHECKTIME = value;
            }
        }
    }
    
    /// T_BLINDSIGNEntity执行类
    public abstract class T_BLINDSIGNEntityAction
    {
        
        public T_BLINDSIGNEntityAction()
        {
        }
        
        public static void Save(T_BLINDSIGNEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_BLINDSIGNEntity RetrieveAT_BLINDSIGNEntity(decimal ID)
        {
            T_BLINDSIGNEntity obj=new T_BLINDSIGNEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_BLINDSIGNEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_BLINDSIGNEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_BLINDSIGNEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_BLINDSIGNEntity));
            return rc.AsDataTable();
        }
    }
}
