//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/11 13:36:27
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_BLINDMEMBEREntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>BLINDSN</summary>
        public const string @__BLINDSN = "BLINDSN";
        
        /// <summary>NAME</summary>
        public const string @__NAME = "NAME";
        
        /// <summary>SEX</summary>
        public const string @__SEX = "SEX";
        
        /// <summary>BIRTHDAY</summary>
        public const string @__BIRTHDAY = "BIRTHDAY";
        
        /// <summary>AGE</summary>
        public const string @__AGE = "AGE";
        
        /// <summary>MARRYHIS</summary>
        public const string @__MARRYHIS = "MARRYHIS";
        
        /// <summary>PICURL</summary>
        public const string @__PICURL = "PICURL";
        
        /// <summary>EDULV</summary>
        public const string @__EDULV = "EDULV";
        
        /// <summary>IDCARDNUM</summary>
        public const string @__IDCARDNUM = "IDCARDNUM";
        
        /// <summary>QQCODE</summary>
        public const string @__QQCODE = "QQCODE";
        
        /// <summary>WXCODE</summary>
        public const string @__WXCODE = "WXCODE";
        
        /// <summary>COMPANY</summary>
        public const string @__COMPANY = "COMPANY";
        
        /// <summary>IDENTITY</summary>
        public const string @__IDENTITY = "IDENTITY";
        
        /// <summary>DISTRICT</summary>
        public const string @__DISTRICT = "DISTRICT";
        
        /// <summary>ADDRESS</summary>
        public const string @__ADDRESS = "ADDRESS";
        
        /// <summary>TELEPHONE</summary>
        public const string @__TELEPHONE = "TELEPHONE";
        
        /// <summary>INCOMING</summary>
        public const string @__INCOMING = "INCOMING";
        
        /// <summary>HEIGHT</summary>
        public const string @__HEIGHT = "HEIGHT";
        
        /// <summary>WEIGHT</summary>
        public const string @__WEIGHT = "WEIGHT";
        
        /// <summary>CHARACTOR</summary>
        public const string @__CHARACTOR = "CHARACTOR";
        
        /// <summary>HOBBY</summary>
        public const string @__HOBBY = "HOBBY";
        
        /// <summary>AGEDOWN</summary>
        public const string @__AGEDOWN = "AGEDOWN";
        
        /// <summary>AGEUP</summary>
        public const string @__AGEUP = "AGEUP";
        
        /// <summary>HEIGHTDOWN</summary>
        public const string @__HEIGHTDOWN = "HEIGHTDOWN";
        
        /// <summary>HEIGHTUP</summary>
        public const string @__HEIGHTUP = "HEIGHTUP";
        
        /// <summary>WEIGHTDOWN</summary>
        public const string @__WEIGHTDOWN = "WEIGHTDOWN";
        
        /// <summary>WEIGHTUP</summary>
        public const string @__WEIGHTUP = "WEIGHTUP";
        
        /// <summary>INCOMINGDOWN</summary>
        public const string @__INCOMINGDOWN = "INCOMINGDOWN";
        
        /// <summary>INCOMINGUP</summary>
        public const string @__INCOMINGUP = "INCOMINGUP";
        
        /// <summary>DISCONDITIONS</summary>
        public const string @__DISCONDITIONS = "DISCONDITIONS";
        
        /// <summary>OTHERREQUIRE</summary>
        public const string @__OTHERREQUIRE = "OTHERREQUIRE";
        
        /// <summary>INTRODUCE</summary>
        public const string @__INTRODUCE = "INTRODUCE";
        
        /// <summary>ENTERTIME</summary>
        public const string @__ENTERTIME = "ENTERTIME";
        
        /// <summary>USERNAME</summary>
        public const string @__USERNAME = "USERNAME";
        
        /// <summary>INSERTTIME</summary>
        public const string @__INSERTTIME = "INSERTTIME";
        
        /// <summary>STATUS</summary>
        public const string @__STATUS = "STATUS";
        
        private decimal m_ID;
        
        private string m_BLINDSN;
        
        private string m_NAME;
        
        private string m_SEX;
        
        private System.DateTime m_BIRTHDAY = DateTime.MinValue;
        
        private decimal m_AGE;
        
        private string m_MARRYHIS;
        
        private string m_PICURL;
        
        private string m_EDULV;
        
        private string m_IDCARDNUM;
        
        private string m_QQCODE;
        
        private string m_WXCODE;
        
        private string m_COMPANY;
        
        private string m_IDENTITY;
        
        private string m_DISTRICT;
        
        private string m_ADDRESS;
        
        private string m_TELEPHONE;
        
        private decimal m_INCOMING;
        
        private decimal m_HEIGHT;
        
        private decimal m_WEIGHT;
        
        private string m_CHARACTOR;
        
        private string m_HOBBY;
        
        private decimal m_AGEDOWN;
        
        private decimal m_AGEUP;
        
        private decimal m_HEIGHTDOWN;
        
        private decimal m_HEIGHTUP;
        
        private decimal m_WEIGHTDOWN;
        
        private decimal m_WEIGHTUP;
        
        private decimal m_INCOMINGDOWN;
        
        private decimal m_INCOMINGUP;
        
        private string m_DISCONDITIONS;
        
        private string m_OTHERREQUIRE;
        
        private string m_INTRODUCE;
        
        private System.DateTime m_ENTERTIME = DateTime.MinValue;
        
        private string m_USERNAME;
        
        private System.DateTime m_INSERTTIME = DateTime.MinValue;
        
        private decimal m_STATUS;
        
        /// <summary>构造函数</summary>
        public T_BLINDMEMBEREntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性BLINDSN </summary>
        public string BLINDSN
        {
            get
            {
                return this.m_BLINDSN;
            }
            set
            {
                this.m_BLINDSN = value;
            }
        }
        
        /// <summary>属性NAME </summary>
        public string NAME
        {
            get
            {
                return this.m_NAME;
            }
            set
            {
                this.m_NAME = value;
            }
        }
        
        /// <summary>属性SEX </summary>
        public string SEX
        {
            get
            {
                return this.m_SEX;
            }
            set
            {
                this.m_SEX = value;
            }
        }
        
        /// <summary>属性BIRTHDAY </summary>
        public System.DateTime BIRTHDAY
        {
            get
            {
                return this.m_BIRTHDAY;
            }
            set
            {
                this.m_BIRTHDAY = value;
            }
        }
        
        /// <summary>属性AGE </summary>
        public decimal AGE
        {
            get
            {
                return this.m_AGE;
            }
            set
            {
                this.m_AGE = value;
            }
        }
        
        /// <summary>属性MARRYHIS </summary>
        public string MARRYHIS
        {
            get
            {
                return this.m_MARRYHIS;
            }
            set
            {
                this.m_MARRYHIS = value;
            }
        }
        
        /// <summary>属性PICURL </summary>
        public string PICURL
        {
            get
            {
                return this.m_PICURL;
            }
            set
            {
                this.m_PICURL = value;
            }
        }
        
        /// <summary>属性EDULV </summary>
        public string EDULV
        {
            get
            {
                return this.m_EDULV;
            }
            set
            {
                this.m_EDULV = value;
            }
        }
        
        /// <summary>属性IDCARDNUM </summary>
        public string IDCARDNUM
        {
            get
            {
                return this.m_IDCARDNUM;
            }
            set
            {
                this.m_IDCARDNUM = value;
            }
        }
        
        /// <summary>属性QQCODE </summary>
        public string QQCODE
        {
            get
            {
                return this.m_QQCODE;
            }
            set
            {
                this.m_QQCODE = value;
            }
        }
        
        /// <summary>属性WXCODE </summary>
        public string WXCODE
        {
            get
            {
                return this.m_WXCODE;
            }
            set
            {
                this.m_WXCODE = value;
            }
        }
        
        /// <summary>属性COMPANY </summary>
        public string COMPANY
        {
            get
            {
                return this.m_COMPANY;
            }
            set
            {
                this.m_COMPANY = value;
            }
        }
        
        /// <summary>属性IDENTITY </summary>
        public string IDENTITY
        {
            get
            {
                return this.m_IDENTITY;
            }
            set
            {
                this.m_IDENTITY = value;
            }
        }
        
        /// <summary>属性DISTRICT </summary>
        public string DISTRICT
        {
            get
            {
                return this.m_DISTRICT;
            }
            set
            {
                this.m_DISTRICT = value;
            }
        }
        
        /// <summary>属性ADDRESS </summary>
        public string ADDRESS
        {
            get
            {
                return this.m_ADDRESS;
            }
            set
            {
                this.m_ADDRESS = value;
            }
        }
        
        /// <summary>属性TELEPHONE </summary>
        public string TELEPHONE
        {
            get
            {
                return this.m_TELEPHONE;
            }
            set
            {
                this.m_TELEPHONE = value;
            }
        }
        
        /// <summary>属性INCOMING </summary>
        public decimal INCOMING
        {
            get
            {
                return this.m_INCOMING;
            }
            set
            {
                this.m_INCOMING = value;
            }
        }
        
        /// <summary>属性HEIGHT </summary>
        public decimal HEIGHT
        {
            get
            {
                return this.m_HEIGHT;
            }
            set
            {
                this.m_HEIGHT = value;
            }
        }
        
        /// <summary>属性WEIGHT </summary>
        public decimal WEIGHT
        {
            get
            {
                return this.m_WEIGHT;
            }
            set
            {
                this.m_WEIGHT = value;
            }
        }
        
        /// <summary>属性CHARACTOR </summary>
        public string CHARACTOR
        {
            get
            {
                return this.m_CHARACTOR;
            }
            set
            {
                this.m_CHARACTOR = value;
            }
        }
        
        /// <summary>属性HOBBY </summary>
        public string HOBBY
        {
            get
            {
                return this.m_HOBBY;
            }
            set
            {
                this.m_HOBBY = value;
            }
        }
        
        /// <summary>属性AGEDOWN </summary>
        public decimal AGEDOWN
        {
            get
            {
                return this.m_AGEDOWN;
            }
            set
            {
                this.m_AGEDOWN = value;
            }
        }
        
        /// <summary>属性AGEUP </summary>
        public decimal AGEUP
        {
            get
            {
                return this.m_AGEUP;
            }
            set
            {
                this.m_AGEUP = value;
            }
        }
        
        /// <summary>属性HEIGHTDOWN </summary>
        public decimal HEIGHTDOWN
        {
            get
            {
                return this.m_HEIGHTDOWN;
            }
            set
            {
                this.m_HEIGHTDOWN = value;
            }
        }
        
        /// <summary>属性HEIGHTUP </summary>
        public decimal HEIGHTUP
        {
            get
            {
                return this.m_HEIGHTUP;
            }
            set
            {
                this.m_HEIGHTUP = value;
            }
        }
        
        /// <summary>属性WEIGHTDOWN </summary>
        public decimal WEIGHTDOWN
        {
            get
            {
                return this.m_WEIGHTDOWN;
            }
            set
            {
                this.m_WEIGHTDOWN = value;
            }
        }
        
        /// <summary>属性WEIGHTUP </summary>
        public decimal WEIGHTUP
        {
            get
            {
                return this.m_WEIGHTUP;
            }
            set
            {
                this.m_WEIGHTUP = value;
            }
        }
        
        /// <summary>属性INCOMINGDOWN </summary>
        public decimal INCOMINGDOWN
        {
            get
            {
                return this.m_INCOMINGDOWN;
            }
            set
            {
                this.m_INCOMINGDOWN = value;
            }
        }
        
        /// <summary>属性INCOMINGUP </summary>
        public decimal INCOMINGUP
        {
            get
            {
                return this.m_INCOMINGUP;
            }
            set
            {
                this.m_INCOMINGUP = value;
            }
        }
        
        /// <summary>属性DISCONDITIONS </summary>
        public string DISCONDITIONS
        {
            get
            {
                return this.m_DISCONDITIONS;
            }
            set
            {
                this.m_DISCONDITIONS = value;
            }
        }
        
        /// <summary>属性OTHERREQUIRE </summary>
        public string OTHERREQUIRE
        {
            get
            {
                return this.m_OTHERREQUIRE;
            }
            set
            {
                this.m_OTHERREQUIRE = value;
            }
        }
        
        /// <summary>属性INTRODUCE </summary>
        public string INTRODUCE
        {
            get
            {
                return this.m_INTRODUCE;
            }
            set
            {
                this.m_INTRODUCE = value;
            }
        }
        
        /// <summary>属性ENTERTIME </summary>
        public System.DateTime ENTERTIME
        {
            get
            {
                return this.m_ENTERTIME;
            }
            set
            {
                this.m_ENTERTIME = value;
            }
        }
        
        /// <summary>属性USERNAME </summary>
        public string USERNAME
        {
            get
            {
                return this.m_USERNAME;
            }
            set
            {
                this.m_USERNAME = value;
            }
        }
        
        /// <summary>属性INSERTTIME </summary>
        public System.DateTime INSERTTIME
        {
            get
            {
                return this.m_INSERTTIME;
            }
            set
            {
                this.m_INSERTTIME = value;
            }
        }
        
        /// <summary>属性STATUS </summary>
        public decimal STATUS
        {
            get
            {
                return this.m_STATUS;
            }
            set
            {
                this.m_STATUS = value;
            }
        }
    }
    
    /// T_BLINDMEMBEREntity执行类
    public abstract class T_BLINDMEMBEREntityAction
    {
        
        private T_BLINDMEMBEREntityAction()
        {
        }
        
        public static void Save(T_BLINDMEMBEREntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_BLINDMEMBEREntity RetrieveAT_BLINDMEMBEREntity(decimal ID)
        {
            T_BLINDMEMBEREntity obj=new T_BLINDMEMBEREntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_BLINDMEMBEREntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_BLINDMEMBEREntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_BLINDMEMBEREntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_BLINDMEMBEREntity));
            return rc.AsDataTable();
        }
    }
}
