//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/30 19:04:56
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_BLINDMSGEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>FROMBLINDID</summary>
        public const string @__FROMBLINDID = "FROMBLINDID";
        
        /// <summary>TOBLINDID</summary>
        public const string @__TOBLINDID = "TOBLINDID";
        
        /// <summary>MSG</summary>
        public const string @__MSG = "MSG";
        
        private decimal m_ID;
        
        private decimal m_FROMBLINDID;
        
        private decimal m_TOBLINDID;
        
        private string m_MSG;
        
        /// <summary>构造函数</summary>
        public T_BLINDMSGEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性FROMBLINDID </summary>
        public decimal FROMBLINDID
        {
            get
            {
                return this.m_FROMBLINDID;
            }
            set
            {
                this.m_FROMBLINDID = value;
            }
        }
        
        /// <summary>属性TOBLINDID </summary>
        public decimal TOBLINDID
        {
            get
            {
                return this.m_TOBLINDID;
            }
            set
            {
                this.m_TOBLINDID = value;
            }
        }
        
        /// <summary>属性MSG </summary>
        public string MSG
        {
            get
            {
                return this.m_MSG;
            }
            set
            {
                this.m_MSG = value;
            }
        }
    }
    
    /// T_BLINDMSGEntity执行类
    public abstract class T_BLINDMSGEntityAction
    {
        
        public T_BLINDMSGEntityAction()
        {
        }
        
        public static void Save(T_BLINDMSGEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_BLINDMSGEntity RetrieveAT_BLINDMSGEntity(decimal ID)
        {
            T_BLINDMSGEntity obj=new T_BLINDMSGEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_BLINDMSGEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_BLINDMSGEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_BLINDMSGEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_BLINDMSGEntity));
            return rc.AsDataTable();
        }
    }
}
