//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/11 13:36:27
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_DOCTORHELPPICEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>DOCTORHELPID</summary>
        public const string @__DOCTORHELPID = "DOCTORHELPID";
        
        /// <summary>PICURL</summary>
        public const string @__PICURL = "PICURL";
        
        private decimal m_ID;
        
        private decimal m_DOCTORHELPID;
        
        private string m_PICURL;
        
        /// <summary>构造函数</summary>
        public T_DOCTORHELPPICEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性DOCTORHELPID </summary>
        public decimal DOCTORHELPID
        {
            get
            {
                return this.m_DOCTORHELPID;
            }
            set
            {
                this.m_DOCTORHELPID = value;
            }
        }
        
        /// <summary>属性PICURL </summary>
        public string PICURL
        {
            get
            {
                return this.m_PICURL;
            }
            set
            {
                this.m_PICURL = value;
            }
        }
    }
    
    /// T_DOCTORHELPPICEntity执行类
    public abstract class T_DOCTORHELPPICEntityAction
    {
        
        private T_DOCTORHELPPICEntityAction()
        {
        }
        
        public static void Save(T_DOCTORHELPPICEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_DOCTORHELPPICEntity RetrieveAT_DOCTORHELPPICEntity(decimal ID)
        {
            T_DOCTORHELPPICEntity obj=new T_DOCTORHELPPICEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_DOCTORHELPPICEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_DOCTORHELPPICEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_DOCTORHELPPICEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_DOCTORHELPPICEntity));
            return rc.AsDataTable();
        }
    }
}
