//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/19 13:22:15
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_ENTERPRISE_ORDERLISTEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>SN</summary>
        public const string @__SN = "SN";
        
        /// <summary>ORDERTYPE</summary>
        public const string @__ORDERTYPE = "ORDERTYPE";
        
        /// <summary>SERVICENAME</summary>
        public const string @__SERVICENAME = "SERVICENAME";
        
        /// <summary>ENTERPRISEID</summary>
        public const string @__ENTERPRISEID = "ENTERPRISEID";
        
        /// <summary>ENTERPRISENAME</summary>
        public const string @__ENTERPRISENAME = "ENTERPRISENAME";
        
        /// <summary>USERID</summary>
        public const string @__USERID = "USERID";
        
        /// <summary>LOGINNAME</summary>
        public const string @__LOGINNAME = "LOGINNAME";
        
        /// <summary>USERNAME</summary>
        public const string @__USERNAME = "USERNAME";
        
        /// <summary>MOBILE</summary>
        public const string @__MOBILE = "MOBILE";
        
        /// <summary>OTHERPHONE</summary>
        public const string @__OTHERPHONE = "OTHERPHONE";
        
        /// <summary>ADDRESS</summary>
        public const string @__ADDRESS = "ADDRESS";
        
        /// <summary>ORDERTIME</summary>
        public const string @__ORDERTIME = "ORDERTIME";
        
        /// <summary>FWFS</summary>
        public const string @__FWFS = "FWFS";
        
        /// <summary>FWYQ</summary>
        public const string @__FWYQ = "FWYQ";
        
        /// <summary>FWBZ</summary>
        public const string @__FWBZ = "FWBZ";
        
        /// <summary>JTDBJ</summary>
        public const string @__JTDBJ = "JTDBJ";
        
        /// <summary>JTDTIME</summary>
        public const string @__JTDTIME = "JTDTIME";
        
        /// <summary>JTDUSER</summary>
        public const string @__JTDUSER = "JTDUSER";
        
        /// <summary>TDLY</summary>
        public const string @__TDLY = "TDLY";
        
        /// <summary>TDLX</summary>
        public const string @__TDLX = "TDLX";
        
        /// <summary>WCBJ</summary>
        public const string @__WCBJ = "WCBJ";
        
        /// <summary>WCTIME</summary>
        public const string @__WCTIME = "WCTIME";
        
        /// <summary>WCUSER</summary>
        public const string @__WCUSER = "WCUSER";
        
        /// <summary>FWQKMS</summary>
        public const string @__FWQKMS = "FWQKMS";
        
        /// <summary>ZZFWSJ</summary>
        public const string @__ZZFWSJ = "ZZFWSJ";
        
        /// <summary>ZZFWJG</summary>
        public const string @__ZZFWJG = "ZZFWJG";
        
        /// <summary>PJBJ</summary>
        public const string @__PJBJ = "PJBJ";
        
        /// <summary>PJSJ</summary>
        public const string @__PJSJ = "PJSJ";
        
        /// <summary>SHBJ</summary>
        public const string @__SHBJ = "SHBJ";
        
        /// <summary>SHSJ</summary>
        public const string @__SHSJ = "SHSJ";
        
        /// <summary>STATUS</summary>
        public const string @__STATUS = "STATUS";
        
        private decimal m_ID;
        
        private string m_SN;
        
        private string m_ORDERTYPE;
        
        private string m_SERVICENAME;
        
        private decimal m_ENTERPRISEID;
        
        private string m_ENTERPRISENAME;
        
        private string m_USERID;
        
        private string m_LOGINNAME;
        
        private string m_USERNAME;
        
        private string m_MOBILE;
        
        private string m_OTHERPHONE;
        
        private string m_ADDRESS;
        
        private System.DateTime m_ORDERTIME = DateTime.MinValue;
        
        private string m_FWFS;
        
        private string m_FWYQ;
        
        private string m_FWBZ;
        
        private decimal m_JTDBJ;
        
        private System.DateTime m_JTDTIME = DateTime.MinValue;
        
        private string m_JTDUSER;
        
        private string m_TDLY;
        
        private decimal m_TDLX;
        
        private decimal m_WCBJ;
        
        private System.DateTime m_WCTIME = DateTime.MinValue;
        
        private string m_WCUSER;
        
        private string m_FWQKMS;
        
        private string m_ZZFWSJ;
        
        private string m_ZZFWJG;
        
        private decimal m_PJBJ;
        
        private System.DateTime m_PJSJ = DateTime.MinValue;
        
        private decimal m_SHBJ;
        
        private System.DateTime m_SHSJ = DateTime.MinValue;
        
        private decimal m_STATUS;
        
        /// <summary>构造函数</summary>
        public T_ENTERPRISE_ORDERLISTEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性SN </summary>
        public string SN
        {
            get
            {
                return this.m_SN;
            }
            set
            {
                this.m_SN = value;
            }
        }
        
        /// <summary>属性ORDERTYPE </summary>
        public string ORDERTYPE
        {
            get
            {
                return this.m_ORDERTYPE;
            }
            set
            {
                this.m_ORDERTYPE = value;
            }
        }
        
        /// <summary>属性SERVICENAME </summary>
        public string SERVICENAME
        {
            get
            {
                return this.m_SERVICENAME;
            }
            set
            {
                this.m_SERVICENAME = value;
            }
        }
        
        /// <summary>属性ENTERPRISEID </summary>
        public decimal ENTERPRISEID
        {
            get
            {
                return this.m_ENTERPRISEID;
            }
            set
            {
                this.m_ENTERPRISEID = value;
            }
        }
        
        /// <summary>属性ENTERPRISENAME </summary>
        public string ENTERPRISENAME
        {
            get
            {
                return this.m_ENTERPRISENAME;
            }
            set
            {
                this.m_ENTERPRISENAME = value;
            }
        }
        
        /// <summary>属性USERID </summary>
        public string USERID
        {
            get
            {
                return this.m_USERID;
            }
            set
            {
                this.m_USERID = value;
            }
        }
        
        /// <summary>属性LOGINNAME </summary>
        public string LOGINNAME
        {
            get
            {
                return this.m_LOGINNAME;
            }
            set
            {
                this.m_LOGINNAME = value;
            }
        }
        
        /// <summary>属性USERNAME </summary>
        public string USERNAME
        {
            get
            {
                return this.m_USERNAME;
            }
            set
            {
                this.m_USERNAME = value;
            }
        }
        
        /// <summary>属性MOBILE </summary>
        public string MOBILE
        {
            get
            {
                return this.m_MOBILE;
            }
            set
            {
                this.m_MOBILE = value;
            }
        }
        
        /// <summary>属性OTHERPHONE </summary>
        public string OTHERPHONE
        {
            get
            {
                return this.m_OTHERPHONE;
            }
            set
            {
                this.m_OTHERPHONE = value;
            }
        }
        
        /// <summary>属性ADDRESS </summary>
        public string ADDRESS
        {
            get
            {
                return this.m_ADDRESS;
            }
            set
            {
                this.m_ADDRESS = value;
            }
        }
        
        /// <summary>属性ORDERTIME </summary>
        public System.DateTime ORDERTIME
        {
            get
            {
                return this.m_ORDERTIME;
            }
            set
            {
                this.m_ORDERTIME = value;
            }
        }
        
        /// <summary>属性FWFS </summary>
        public string FWFS
        {
            get
            {
                return this.m_FWFS;
            }
            set
            {
                this.m_FWFS = value;
            }
        }
        
        /// <summary>属性FWYQ </summary>
        public string FWYQ
        {
            get
            {
                return this.m_FWYQ;
            }
            set
            {
                this.m_FWYQ = value;
            }
        }
        
        /// <summary>属性FWBZ </summary>
        public string FWBZ
        {
            get
            {
                return this.m_FWBZ;
            }
            set
            {
                this.m_FWBZ = value;
            }
        }
        
        /// <summary>属性JTDBJ </summary>
        public decimal JTDBJ
        {
            get
            {
                return this.m_JTDBJ;
            }
            set
            {
                this.m_JTDBJ = value;
            }
        }
        
        /// <summary>属性JTDTIME </summary>
        public System.DateTime JTDTIME
        {
            get
            {
                return this.m_JTDTIME;
            }
            set
            {
                this.m_JTDTIME = value;
            }
        }
        
        /// <summary>属性JTDUSER </summary>
        public string JTDUSER
        {
            get
            {
                return this.m_JTDUSER;
            }
            set
            {
                this.m_JTDUSER = value;
            }
        }
        
        /// <summary>属性TDLY </summary>
        public string TDLY
        {
            get
            {
                return this.m_TDLY;
            }
            set
            {
                this.m_TDLY = value;
            }
        }
        
        /// <summary>属性TDLX </summary>
        public decimal TDLX
        {
            get
            {
                return this.m_TDLX;
            }
            set
            {
                this.m_TDLX = value;
            }
        }
        
        /// <summary>属性WCBJ </summary>
        public decimal WCBJ
        {
            get
            {
                return this.m_WCBJ;
            }
            set
            {
                this.m_WCBJ = value;
            }
        }
        
        /// <summary>属性WCTIME </summary>
        public System.DateTime WCTIME
        {
            get
            {
                return this.m_WCTIME;
            }
            set
            {
                this.m_WCTIME = value;
            }
        }
        
        /// <summary>属性WCUSER </summary>
        public string WCUSER
        {
            get
            {
                return this.m_WCUSER;
            }
            set
            {
                this.m_WCUSER = value;
            }
        }
        
        /// <summary>属性FWQKMS </summary>
        public string FWQKMS
        {
            get
            {
                return this.m_FWQKMS;
            }
            set
            {
                this.m_FWQKMS = value;
            }
        }
        
        /// <summary>属性ZZFWSJ </summary>
        public string ZZFWSJ
        {
            get
            {
                return this.m_ZZFWSJ;
            }
            set
            {
                this.m_ZZFWSJ = value;
            }
        }
        
        /// <summary>属性ZZFWJG </summary>
        public string ZZFWJG
        {
            get
            {
                return this.m_ZZFWJG;
            }
            set
            {
                this.m_ZZFWJG = value;
            }
        }
        
        /// <summary>属性PJBJ </summary>
        public decimal PJBJ
        {
            get
            {
                return this.m_PJBJ;
            }
            set
            {
                this.m_PJBJ = value;
            }
        }
        
        /// <summary>属性PJSJ </summary>
        public System.DateTime PJSJ
        {
            get
            {
                return this.m_PJSJ;
            }
            set
            {
                this.m_PJSJ = value;
            }
        }
        
        /// <summary>属性SHBJ </summary>
        public decimal SHBJ
        {
            get
            {
                return this.m_SHBJ;
            }
            set
            {
                this.m_SHBJ = value;
            }
        }
        
        /// <summary>属性SHSJ </summary>
        public System.DateTime SHSJ
        {
            get
            {
                return this.m_SHSJ;
            }
            set
            {
                this.m_SHSJ = value;
            }
        }
        
        /// <summary>属性STATUS </summary>
        public decimal STATUS
        {
            get
            {
                return this.m_STATUS;
            }
            set
            {
                this.m_STATUS = value;
            }
        }
    }
    
    /// T_ENTERPRISE_ORDERLISTEntity执行类
    public abstract class T_ENTERPRISE_ORDERLISTEntityAction
    {
        
        public T_ENTERPRISE_ORDERLISTEntityAction()
        {
        }
        
        public static void Save(T_ENTERPRISE_ORDERLISTEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_ENTERPRISE_ORDERLISTEntity RetrieveAT_ENTERPRISE_ORDERLISTEntity(decimal ID)
        {
            T_ENTERPRISE_ORDERLISTEntity obj=new T_ENTERPRISE_ORDERLISTEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_ENTERPRISE_ORDERLISTEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_ENTERPRISE_ORDERLISTEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_ENTERPRISE_ORDERLISTEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_ENTERPRISE_ORDERLISTEntity));
            return rc.AsDataTable();
        }
    }
}
