//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/11 13:36:27
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_JOBWANTEDEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>TITLE</summary>
        public const string @__TITLE = "TITLE";
        
        /// <summary>JOBTYPE</summary>
        public const string @__JOBTYPE = "JOBTYPE";
        
        /// <summary>SALARY</summary>
        public const string @__SALARY = "SALARY";
        
        /// <summary>NAME</summary>
        public const string @__NAME = "NAME";
        
        /// <summary>SEX</summary>
        public const string @__SEX = "SEX";
        
        /// <summary>BIRTHYEAR</summary>
        public const string @__BIRTHYEAR = "BIRTHYEAR";
        
        /// <summary>BIRTHMONEY</summary>
        public const string @__BIRTHMONEY = "BIRTHMONEY";
        
        /// <summary>AGE</summary>
        public const string @__AGE = "AGE";
        
        /// <summary>RESIDENCE</summary>
        public const string @__RESIDENCE = "RESIDENCE";
        
        /// <summary>WORKPLACE</summary>
        public const string @__WORKPLACE = "WORKPLACE";
        
        /// <summary>TELEPHONE</summary>
        public const string @__TELEPHONE = "TELEPHONE";
        
        /// <summary>INTRODUCE</summary>
        public const string @__INTRODUCE = "INTRODUCE";
        
        /// <summary>NATIVE</summary>
        public const string @__NATIVE = "NATIVE";
        
        /// <summary>STATUS</summary>
        public const string @__STATUS = "STATUS";
        
        /// <summary>MEMBERID</summary>
        public const string @__MEMBERID = "MEMBERID";
        
        /// <summary>INSERTTIME</summary>
        public const string @__INSERTTIME = "INSERTTIME";
        
        /// <summary>CHECKTIME</summary>
        public const string @__CHECKTIME = "CHECKTIME";
        
        /// <summary>USERNAME</summary>
        public const string @__USERNAME = "USERNAME";
        
        private decimal m_ID;
        
        private string m_TITLE;
        
        private string m_JOBTYPE;
        
        private string m_SALARY;
        
        private string m_NAME;
        
        private string m_SEX;
        
        private string m_BIRTHYEAR;
        
        private string m_BIRTHMONEY;
        
        private decimal m_AGE;
        
        private string m_RESIDENCE;
        
        private string m_WORKPLACE;
        
        private string m_TELEPHONE;
        
        private string m_INTRODUCE;
        
        private string m_NATIVE;
        
        private decimal m_STATUS;
        
        private decimal m_MEMBERID;
        
        private System.DateTime m_INSERTTIME = DateTime.MinValue;
        
        private System.DateTime m_CHECKTIME = DateTime.MinValue;
        
        private string m_USERNAME;
        
        /// <summary>构造函数</summary>
        public T_JOBWANTEDEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性TITLE </summary>
        public string TITLE
        {
            get
            {
                return this.m_TITLE;
            }
            set
            {
                this.m_TITLE = value;
            }
        }
        
        /// <summary>属性JOBTYPE </summary>
        public string JOBTYPE
        {
            get
            {
                return this.m_JOBTYPE;
            }
            set
            {
                this.m_JOBTYPE = value;
            }
        }
        
        /// <summary>属性SALARY </summary>
        public string SALARY
        {
            get
            {
                return this.m_SALARY;
            }
            set
            {
                this.m_SALARY = value;
            }
        }
        
        /// <summary>属性NAME </summary>
        public string NAME
        {
            get
            {
                return this.m_NAME;
            }
            set
            {
                this.m_NAME = value;
            }
        }
        
        /// <summary>属性SEX </summary>
        public string SEX
        {
            get
            {
                return this.m_SEX;
            }
            set
            {
                this.m_SEX = value;
            }
        }
        
        /// <summary>属性BIRTHYEAR </summary>
        public string BIRTHYEAR
        {
            get
            {
                return this.m_BIRTHYEAR;
            }
            set
            {
                this.m_BIRTHYEAR = value;
            }
        }
        
        /// <summary>属性BIRTHMONEY </summary>
        public string BIRTHMONEY
        {
            get
            {
                return this.m_BIRTHMONEY;
            }
            set
            {
                this.m_BIRTHMONEY = value;
            }
        }
        
        /// <summary>属性AGE </summary>
        public decimal AGE
        {
            get
            {
                return this.m_AGE;
            }
            set
            {
                this.m_AGE = value;
            }
        }
        
        /// <summary>属性RESIDENCE </summary>
        public string RESIDENCE
        {
            get
            {
                return this.m_RESIDENCE;
            }
            set
            {
                this.m_RESIDENCE = value;
            }
        }
        
        /// <summary>属性WORKPLACE </summary>
        public string WORKPLACE
        {
            get
            {
                return this.m_WORKPLACE;
            }
            set
            {
                this.m_WORKPLACE = value;
            }
        }
        
        /// <summary>属性TELEPHONE </summary>
        public string TELEPHONE
        {
            get
            {
                return this.m_TELEPHONE;
            }
            set
            {
                this.m_TELEPHONE = value;
            }
        }
        
        /// <summary>属性INTRODUCE </summary>
        public string INTRODUCE
        {
            get
            {
                return this.m_INTRODUCE;
            }
            set
            {
                this.m_INTRODUCE = value;
            }
        }
        
        /// <summary>属性NATIVE </summary>
        public string NATIVE
        {
            get
            {
                return this.m_NATIVE;
            }
            set
            {
                this.m_NATIVE = value;
            }
        }
        
        /// <summary>属性STATUS </summary>
        public decimal STATUS
        {
            get
            {
                return this.m_STATUS;
            }
            set
            {
                this.m_STATUS = value;
            }
        }
        
        /// <summary>属性MEMBERID </summary>
        public decimal MEMBERID
        {
            get
            {
                return this.m_MEMBERID;
            }
            set
            {
                this.m_MEMBERID = value;
            }
        }
        
        /// <summary>属性INSERTTIME </summary>
        public System.DateTime INSERTTIME
        {
            get
            {
                return this.m_INSERTTIME;
            }
            set
            {
                this.m_INSERTTIME = value;
            }
        }
        
        /// <summary>属性CHECKTIME </summary>
        public System.DateTime CHECKTIME
        {
            get
            {
                return this.m_CHECKTIME;
            }
            set
            {
                this.m_CHECKTIME = value;
            }
        }
        
        /// <summary>属性USERNAME </summary>
        public string USERNAME
        {
            get
            {
                return this.m_USERNAME;
            }
            set
            {
                this.m_USERNAME = value;
            }
        }
    }
    
    /// T_JOBWANTEDEntity执行类
    public abstract class T_JOBWANTEDEntityAction
    {
        
        private T_JOBWANTEDEntityAction()
        {
        }
        
        public static void Save(T_JOBWANTEDEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_JOBWANTEDEntity RetrieveAT_JOBWANTEDEntity(decimal ID)
        {
            T_JOBWANTEDEntity obj=new T_JOBWANTEDEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_JOBWANTEDEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_JOBWANTEDEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_JOBWANTEDEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_JOBWANTEDEntity));
            return rc.AsDataTable();
        }
    }
}
