//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/11 13:36:27
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_LAWHELPEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>HELPTIME</summary>
        public const string @__HELPTIME = "HELPTIME";
        
        /// <summary>HELPCONTENT</summary>
        public const string @__HELPCONTENT = "HELPCONTENT";
        
        /// <summary>NAME</summary>
        public const string @__NAME = "NAME";
        
        /// <summary>SEX</summary>
        public const string @__SEX = "SEX";
        
        /// <summary>TELEPHONE</summary>
        public const string @__TELEPHONE = "TELEPHONE";
        
        /// <summary>LAWID</summary>
        public const string @__LAWID = "LAWID";
        
        /// <summary>REPLYTIME</summary>
        public const string @__REPLYTIME = "REPLYTIME";
        
        /// <summary>REPLYCONTENT</summary>
        public const string @__REPLYCONTENT = "REPLYCONTENT";
        
        /// <summary>STATUS</summary>
        public const string @__STATUS = "STATUS";
        
        /// <summary>USERNAME</summary>
        public const string @__USERNAME = "USERNAME";
        
        /// <summary>CHECKTIME</summary>
        public const string @__CHECKTIME = "CHECKTIME";
        
        private decimal m_ID;
        
        private System.DateTime m_HELPTIME = DateTime.MinValue;
        
        private string m_HELPCONTENT;
        
        private string m_NAME;
        
        private string m_SEX;
        
        private string m_TELEPHONE;
        
        private decimal m_LAWID;
        
        private System.DateTime m_REPLYTIME = DateTime.MinValue;
        
        private string m_REPLYCONTENT;
        
        private decimal m_STATUS;
        
        private string m_USERNAME;
        
        private System.DateTime m_CHECKTIME = DateTime.MinValue;
        
        /// <summary>构造函数</summary>
        public T_LAWHELPEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性HELPTIME </summary>
        public System.DateTime HELPTIME
        {
            get
            {
                return this.m_HELPTIME;
            }
            set
            {
                this.m_HELPTIME = value;
            }
        }
        
        /// <summary>属性HELPCONTENT </summary>
        public string HELPCONTENT
        {
            get
            {
                return this.m_HELPCONTENT;
            }
            set
            {
                this.m_HELPCONTENT = value;
            }
        }
        
        /// <summary>属性NAME </summary>
        public string NAME
        {
            get
            {
                return this.m_NAME;
            }
            set
            {
                this.m_NAME = value;
            }
        }
        
        /// <summary>属性SEX </summary>
        public string SEX
        {
            get
            {
                return this.m_SEX;
            }
            set
            {
                this.m_SEX = value;
            }
        }
        
        /// <summary>属性TELEPHONE </summary>
        public string TELEPHONE
        {
            get
            {
                return this.m_TELEPHONE;
            }
            set
            {
                this.m_TELEPHONE = value;
            }
        }
        
        /// <summary>属性LAWID </summary>
        public decimal LAWID
        {
            get
            {
                return this.m_LAWID;
            }
            set
            {
                this.m_LAWID = value;
            }
        }
        
        /// <summary>属性REPLYTIME </summary>
        public System.DateTime REPLYTIME
        {
            get
            {
                return this.m_REPLYTIME;
            }
            set
            {
                this.m_REPLYTIME = value;
            }
        }
        
        /// <summary>属性REPLYCONTENT </summary>
        public string REPLYCONTENT
        {
            get
            {
                return this.m_REPLYCONTENT;
            }
            set
            {
                this.m_REPLYCONTENT = value;
            }
        }
        
        /// <summary>属性STATUS </summary>
        public decimal STATUS
        {
            get
            {
                return this.m_STATUS;
            }
            set
            {
                this.m_STATUS = value;
            }
        }
        
        /// <summary>属性USERNAME </summary>
        public string USERNAME
        {
            get
            {
                return this.m_USERNAME;
            }
            set
            {
                this.m_USERNAME = value;
            }
        }
        
        /// <summary>属性CHECKTIME </summary>
        public System.DateTime CHECKTIME
        {
            get
            {
                return this.m_CHECKTIME;
            }
            set
            {
                this.m_CHECKTIME = value;
            }
        }
    }
    
    /// T_LAWHELPEntity执行类
    public abstract class T_LAWHELPEntityAction
    {
        
        private T_LAWHELPEntityAction()
        {
        }
        
        public static void Save(T_LAWHELPEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_LAWHELPEntity RetrieveAT_LAWHELPEntity(decimal ID)
        {
            T_LAWHELPEntity obj=new T_LAWHELPEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_LAWHELPEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_LAWHELPEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_LAWHELPEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_LAWHELPEntity));
            return rc.AsDataTable();
        }
    }
}
