//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： lxj1987
//             Created Time： 2016/6/30 19:08:08
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_PRODUCTPICEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>PROID</summary>
        public const string @__PROID = "PROID";
        
        /// <summary>PICURL</summary>
        public const string @__PICURL = "PICURL";
        
        /// <summary>ISTOP</summary>
        public const string @__ISTOP = "ISTOP";
        
        private decimal m_ID;

        private string m_PROID;
        
        private string m_PICURL;
        
        private decimal m_ISTOP;
        
        /// <summary>构造函数</summary>
        public T_PRODUCTPICEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性PROID </summary>
        public string PROID
        {
            get
            {
                return this.m_PROID;
            }
            set
            {
                this.m_PROID = value;
            }
        }
        
        /// <summary>属性PICURL </summary>
        public string PICURL
        {
            get
            {
                return this.m_PICURL;
            }
            set
            {
                this.m_PICURL = value;
            }
        }
        
        /// <summary>属性ISTOP </summary>
        public decimal ISTOP
        {
            get
            {
                return this.m_ISTOP;
            }
            set
            {
                this.m_ISTOP = value;
            }
        }
    }
    
    /// T_PRODUCTPICEntity执行类
    public abstract class T_PRODUCTPICEntityAction
    {
        
        private T_PRODUCTPICEntityAction()
        {
        }
        
        public static void Save(T_PRODUCTPICEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_PRODUCTPICEntity RetrieveAT_PRODUCTPICEntity(decimal ID)
        {
            T_PRODUCTPICEntity obj=new T_PRODUCTPICEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_PRODUCTPICEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_PRODUCTPICEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_PRODUCTPICEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_PRODUCTPICEntity));
            return rc.AsDataTable();
        }
    }
}
