//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/11 13:36:27
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_RENTHOUSEEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>RENTTYPE</summary>
        public const string @__RENTTYPE = "RENTTYPE";
        
        /// <summary>DISTRICT</summary>
        public const string @__DISTRICT = "DISTRICT";
        
        /// <summary>TITLE</summary>
        public const string @__TITLE = "TITLE";
        
        /// <summary>RENTAL</summary>
        public const string @__RENTAL = "RENTAL";
        
        /// <summary>RENTALREQUIRE</summary>
        public const string @__RENTALREQUIRE = "RENTALREQUIRE";
        
        /// <summary>FLOOR</summary>
        public const string @__FLOOR = "FLOOR";
        
        /// <summary>ALLFLOOR</summary>
        public const string @__ALLFLOOR = "ALLFLOOR";
        
        /// <summary>ROOM</summary>
        public const string @__ROOM = "ROOM";
        
        /// <summary>HALL</summary>
        public const string @__HALL = "HALL";
        
        /// <summary>TOILET</summary>
        public const string @__TOILET = "TOILET";
        
        /// <summary>AREA</summary>
        public const string @__AREA = "AREA";
        
        /// <summary>HOUSETYPE</summary>
        public const string @__HOUSETYPE = "HOUSETYPE";
        
        /// <summary>DECORATION</summary>
        public const string @__DECORATION = "DECORATION";
        
        /// <summary>TOWARD</summary>
        public const string @__TOWARD = "TOWARD";
        
        /// <summary>HOUSECONFIG</summary>
        public const string @__HOUSECONFIG = "HOUSECONFIG";
        
        /// <summary>CONTENT</summary>
        public const string @__CONTENT = "CONTENT";
        
        /// <summary>LINKMAN</summary>
        public const string @__LINKMAN = "LINKMAN";
        
        /// <summary>LINKPHONE</summary>
        public const string @__LINKPHONE = "LINKPHONE";
        
        /// <summary>QQCODE</summary>
        public const string @__QQCODE = "QQCODE";
        
        /// <summary>STATUS</summary>
        public const string @__STATUS = "STATUS";
        
        /// <summary>MEMBERID</summary>
        public const string @__MEMBERID = "MEMBERID";
        
        /// <summary>INSERTTIME</summary>
        public const string @__INSERTTIME = "INSERTTIME";
        
        /// <summary>CHECKTIME</summary>
        public const string @__CHECKTIME = "CHECKTIME";
        
        /// <summary>USERNAME</summary>
        public const string @__USERNAME = "USERNAME";

        /// <summary>SECHOUSEID</summary>
        public const string @__SECHOUSEID = "SECHOUSEID";
        
        private decimal m_ID;
        
        private decimal m_RENTTYPE;
        
        private string m_DISTRICT;
        
        private string m_TITLE;
        
        private decimal m_RENTAL;
        
        private string m_RENTALREQUIRE;
        
        private decimal m_FLOOR;
        
        private decimal m_ALLFLOOR;
        
        private decimal m_ROOM;
        
        private decimal m_HALL;
        
        private decimal m_TOILET;
        
        private decimal m_AREA;
        
        private string m_HOUSETYPE;
        
        private string m_DECORATION;
        
        private string m_TOWARD;
        
        private string m_HOUSECONFIG;
        
        private string m_CONTENT;
        
        private string m_LINKMAN;
        
        private string m_LINKPHONE;
        
        private string m_QQCODE;
        
        private decimal m_STATUS;
        
        private decimal m_MEMBERID;
        
        private System.DateTime m_INSERTTIME = DateTime.MinValue;
        
        private System.DateTime m_CHECKTIME = DateTime.MinValue;

        private string m_SECHOUSEID;
        
        private string m_USERNAME;
        
        /// <summary>构造函数</summary>
        public T_RENTHOUSEEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性RENTTYPE </summary>
        public decimal RENTTYPE
        {
            get
            {
                return this.m_RENTTYPE;
            }
            set
            {
                this.m_RENTTYPE = value;
            }
        }
        
        /// <summary>属性DISTRICT </summary>
        public string DISTRICT
        {
            get
            {
                return this.m_DISTRICT;
            }
            set
            {
                this.m_DISTRICT = value;
            }
        }
        
        /// <summary>属性TITLE </summary>
        public string TITLE
        {
            get
            {
                return this.m_TITLE;
            }
            set
            {
                this.m_TITLE = value;
            }
        }
        
        /// <summary>属性RENTAL </summary>
        public decimal RENTAL
        {
            get
            {
                return this.m_RENTAL;
            }
            set
            {
                this.m_RENTAL = value;
            }
        }
        
        /// <summary>属性RENTALREQUIRE </summary>
        public string RENTALREQUIRE
        {
            get
            {
                return this.m_RENTALREQUIRE;
            }
            set
            {
                this.m_RENTALREQUIRE = value;
            }
        }
        
        /// <summary>属性FLOOR </summary>
        public decimal FLOOR
        {
            get
            {
                return this.m_FLOOR;
            }
            set
            {
                this.m_FLOOR = value;
            }
        }
        
        /// <summary>属性ALLFLOOR </summary>
        public decimal ALLFLOOR
        {
            get
            {
                return this.m_ALLFLOOR;
            }
            set
            {
                this.m_ALLFLOOR = value;
            }
        }
        
        /// <summary>属性ROOM </summary>
        public decimal ROOM
        {
            get
            {
                return this.m_ROOM;
            }
            set
            {
                this.m_ROOM = value;
            }
        }
        
        /// <summary>属性HALL </summary>
        public decimal HALL
        {
            get
            {
                return this.m_HALL;
            }
            set
            {
                this.m_HALL = value;
            }
        }
        
        /// <summary>属性TOILET </summary>
        public decimal TOILET
        {
            get
            {
                return this.m_TOILET;
            }
            set
            {
                this.m_TOILET = value;
            }
        }
        
        /// <summary>属性AREA </summary>
        public decimal AREA
        {
            get
            {
                return this.m_AREA;
            }
            set
            {
                this.m_AREA = value;
            }
        }
        
        /// <summary>属性HOUSETYPE </summary>
        public string HOUSETYPE
        {
            get
            {
                return this.m_HOUSETYPE;
            }
            set
            {
                this.m_HOUSETYPE = value;
            }
        }
        
        /// <summary>属性DECORATION </summary>
        public string DECORATION
        {
            get
            {
                return this.m_DECORATION;
            }
            set
            {
                this.m_DECORATION = value;
            }
        }
        
        /// <summary>属性TOWARD </summary>
        public string TOWARD
        {
            get
            {
                return this.m_TOWARD;
            }
            set
            {
                this.m_TOWARD = value;
            }
        }
        
        /// <summary>属性HOUSECONFIG </summary>
        public string HOUSECONFIG
        {
            get
            {
                return this.m_HOUSECONFIG;
            }
            set
            {
                this.m_HOUSECONFIG = value;
            }
        }
        
        /// <summary>属性CONTENT </summary>
        public string CONTENT
        {
            get
            {
                return this.m_CONTENT;
            }
            set
            {
                this.m_CONTENT = value;
            }
        }
        
        /// <summary>属性LINKMAN </summary>
        public string LINKMAN
        {
            get
            {
                return this.m_LINKMAN;
            }
            set
            {
                this.m_LINKMAN = value;
            }
        }
        
        /// <summary>属性LINKPHONE </summary>
        public string LINKPHONE
        {
            get
            {
                return this.m_LINKPHONE;
            }
            set
            {
                this.m_LINKPHONE = value;
            }
        }
        
        /// <summary>属性QQCODE </summary>
        public string QQCODE
        {
            get
            {
                return this.m_QQCODE;
            }
            set
            {
                this.m_QQCODE = value;
            }
        }
        
        /// <summary>属性STATUS </summary>
        public decimal STATUS
        {
            get
            {
                return this.m_STATUS;
            }
            set
            {
                this.m_STATUS = value;
            }
        }
        
        /// <summary>属性MEMBERID </summary>
        public decimal MEMBERID
        {
            get
            {
                return this.m_MEMBERID;
            }
            set
            {
                this.m_MEMBERID = value;
            }
        }
        
        /// <summary>属性INSERTTIME </summary>
        public System.DateTime INSERTTIME
        {
            get
            {
                return this.m_INSERTTIME;
            }
            set
            {
                this.m_INSERTTIME = value;
            }
        }
        
        /// <summary>属性CHECKTIME </summary>
        public System.DateTime CHECKTIME
        {
            get
            {
                return this.m_CHECKTIME;
            }
            set
            {
                this.m_CHECKTIME = value;
            }
        }
        
        /// <summary>属性USERNAME </summary>
        public string USERNAME
        {
            get
            {
                return this.m_USERNAME;
            }
            set
            {
                this.m_USERNAME = value;
            }
        }

        /// <summary>属性SECHOUSEID </summary>
        public string SECHOUSEID
        {
            get
            {
                return this.m_SECHOUSEID;
            }
            set
            {
                this.m_SECHOUSEID = value;
            }
        }

    }
    
    /// T_RENTHOUSEEntity执行类
    public abstract class T_RENTHOUSEEntityAction
    {
        
        private T_RENTHOUSEEntityAction()
        {
        }
        
        public static void Save(T_RENTHOUSEEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_RENTHOUSEEntity RetrieveAT_RENTHOUSEEntity(decimal ID)
        {
            T_RENTHOUSEEntity obj=new T_RENTHOUSEEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_RENTHOUSEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_RENTHOUSEEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_RENTHOUSEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_RENTHOUSEEntity));
            return rc.AsDataTable();
        }
    }
}
