//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/11 13:36:27
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_RECRUITEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>COMPANYNAME</summary>
        public const string @__COMPANYNAME = "COMPANYNAME";
        
        /// <summary>INDUSTRY</summary>
        public const string @__INDUSTRY = "INDUSTRY";
        
        /// <summary>COMPANYNATURE</summary>
        public const string @__COMPANYNATURE = "COMPANYNATURE";
        
        /// <summary>COMPANYSIZE</summary>
        public const string @__COMPANYSIZE = "COMPANYSIZE";
        
        /// <summary>COMPANYINFO</summary>
        public const string @__COMPANYINFO = "COMPANYINFO";
        
        /// <summary>COMPANYBENIFITS</summary>
        public const string @__COMPANYBENIFITS = "COMPANYBENIFITS";
        
        /// <summary>LINKMAN</summary>
        public const string @__LINKMAN = "LINKMAN";
        
        /// <summary>LINKPHONE</summary>
        public const string @__LINKPHONE = "LINKPHONE";
        
        /// <summary>LINKMAIL</summary>
        public const string @__LINKMAIL = "LINKMAIL";
        
        /// <summary>WEBURL</summary>
        public const string @__WEBURL = "WEBURL";
        
        /// <summary>ADDRESS</summary>
        public const string @__ADDRESS = "ADDRESS";
        
        /// <summary>STATUS</summary>
        public const string @__STATUS = "STATUS";
        
        /// <summary>MEMBERID</summary>
        public const string @__MEMBERID = "MEMBERID";
        
        /// <summary>INSERTTIME</summary>
        public const string @__INSERTTIME = "INSERTTIME";
        
        /// <summary>CHECKTIME</summary>
        public const string @__CHECKTIME = "CHECKTIME";
        
        /// <summary>USERNAME</summary>
        public const string @__USERNAME = "USERNAME";
        
        private decimal m_ID;
        
        private string m_COMPANYNAME;
        
        private string m_INDUSTRY;
        
        private string m_COMPANYNATURE;
        
        private string m_COMPANYSIZE;
        
        private string m_COMPANYINFO;
        
        private string m_COMPANYBENIFITS;
        
        private string m_LINKMAN;
        
        private string m_LINKPHONE;
        
        private string m_LINKMAIL;
        
        private string m_WEBURL;
        
        private string m_ADDRESS;
        
        private decimal m_STATUS;
        
        private decimal m_MEMBERID;
        
        private System.DateTime m_INSERTTIME = DateTime.MinValue;
        
        private System.DateTime m_CHECKTIME = DateTime.MinValue;
        
        private string m_USERNAME;
        
        /// <summary>构造函数</summary>
        public T_RECRUITEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性COMPANYNAME </summary>
        public string COMPANYNAME
        {
            get
            {
                return this.m_COMPANYNAME;
            }
            set
            {
                this.m_COMPANYNAME = value;
            }
        }
        
        /// <summary>属性INDUSTRY </summary>
        public string INDUSTRY
        {
            get
            {
                return this.m_INDUSTRY;
            }
            set
            {
                this.m_INDUSTRY = value;
            }
        }
        
        /// <summary>属性COMPANYNATURE </summary>
        public string COMPANYNATURE
        {
            get
            {
                return this.m_COMPANYNATURE;
            }
            set
            {
                this.m_COMPANYNATURE = value;
            }
        }
        
        /// <summary>属性COMPANYSIZE </summary>
        public string COMPANYSIZE
        {
            get
            {
                return this.m_COMPANYSIZE;
            }
            set
            {
                this.m_COMPANYSIZE = value;
            }
        }
        
        /// <summary>属性COMPANYINFO </summary>
        public string COMPANYINFO
        {
            get
            {
                return this.m_COMPANYINFO;
            }
            set
            {
                this.m_COMPANYINFO = value;
            }
        }
        
        /// <summary>属性COMPANYBENIFITS </summary>
        public string COMPANYBENIFITS
        {
            get
            {
                return this.m_COMPANYBENIFITS;
            }
            set
            {
                this.m_COMPANYBENIFITS = value;
            }
        }
        
        /// <summary>属性LINKMAN </summary>
        public string LINKMAN
        {
            get
            {
                return this.m_LINKMAN;
            }
            set
            {
                this.m_LINKMAN = value;
            }
        }
        
        /// <summary>属性LINKPHONE </summary>
        public string LINKPHONE
        {
            get
            {
                return this.m_LINKPHONE;
            }
            set
            {
                this.m_LINKPHONE = value;
            }
        }
        
        /// <summary>属性LINKMAIL </summary>
        public string LINKMAIL
        {
            get
            {
                return this.m_LINKMAIL;
            }
            set
            {
                this.m_LINKMAIL = value;
            }
        }
        
        /// <summary>属性WEBURL </summary>
        public string WEBURL
        {
            get
            {
                return this.m_WEBURL;
            }
            set
            {
                this.m_WEBURL = value;
            }
        }
        
        /// <summary>属性ADDRESS </summary>
        public string ADDRESS
        {
            get
            {
                return this.m_ADDRESS;
            }
            set
            {
                this.m_ADDRESS = value;
            }
        }
        
        /// <summary>属性STATUS </summary>
        public decimal STATUS
        {
            get
            {
                return this.m_STATUS;
            }
            set
            {
                this.m_STATUS = value;
            }
        }
        
        /// <summary>属性MEMBERID </summary>
        public decimal MEMBERID
        {
            get
            {
                return this.m_MEMBERID;
            }
            set
            {
                this.m_MEMBERID = value;
            }
        }
        
        /// <summary>属性INSERTTIME </summary>
        public System.DateTime INSERTTIME
        {
            get
            {
                return this.m_INSERTTIME;
            }
            set
            {
                this.m_INSERTTIME = value;
            }
        }
        
        /// <summary>属性CHECKTIME </summary>
        public System.DateTime CHECKTIME
        {
            get
            {
                return this.m_CHECKTIME;
            }
            set
            {
                this.m_CHECKTIME = value;
            }
        }
        
        /// <summary>属性USERNAME </summary>
        public string USERNAME
        {
            get
            {
                return this.m_USERNAME;
            }
            set
            {
                this.m_USERNAME = value;
            }
        }
    }
    
    /// T_RECRUITEntity执行类
    public abstract class T_RECRUITEntityAction
    {
        
        private T_RECRUITEntityAction()
        {
        }
        
        public static void Save(T_RECRUITEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_RECRUITEntity RetrieveAT_RECRUITEntity(decimal ID)
        {
            T_RECRUITEntity obj=new T_RECRUITEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_RECRUITEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_RECRUITEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_RECRUITEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_RECRUITEntity));
            return rc.AsDataTable();
        }
    }
}
