//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/19 13:22:15
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_SERVICEENTERPRISEEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>TRANSACTORID</summary>
        public const string @__TRANSACTORID = "TRANSACTORID";
        
        /// <summary>TRANSACTIONID</summary>
        public const string @__TRANSACTIONID = "TRANSACTIONID";
        
        /// <summary>ENTERPRISEID</summary>
        public const string @__ENTERPRISEID = "ENTERPRISEID";
        
        /// <summary>ISVOLUNTEER</summary>
        public const string @__ISVOLUNTEER = "ISVOLUNTEER";
        
        /// <summary>DEALTIME</summary>
        public const string @__DEALTIME = "DEALTIME";
        
        /// <summary>ISROUTER</summary>
        public const string @__ISROUTER = "ISROUTER";
        
        /// <summary>HASTRACED</summary>
        public const string @__HASTRACED = "HASTRACED";
        
        /// <summary>ISSERVICE</summary>
        public const string @__ISSERVICE = "ISSERVICE";
        
        /// <summary>REMARK</summary>
        public const string @__REMARK = "REMARK";
        
        /// <summary>ISBACK</summary>
        public const string @__ISBACK = "ISBACK";
        
        /// <summary>ENTERTYPE</summary>
        public const string @__ENTERTYPE = "ENTERTYPE";
        
        /// <summary>OWNMONEY</summary>
        public const string @__OWNMONEY = "OWNMONEY";
        
        /// <summary>ISASSISTANCER</summary>
        public const string @__ISASSISTANCER = "ISASSISTANCER";
        
        /// <summary>ASSISTANCERID</summary>
        public const string @__ASSISTANCERID = "ASSISTANCERID";
        
        /// <summary>HAVEMONEY</summary>
        public const string @__HAVEMONEY = "HAVEMONEY";
        
        /// <summary>SERVICETIME</summary>
        public const string @__SERVICETIME = "SERVICETIME";
        
        private decimal m_ID;
        
        private string m_TRANSACTORID;
        
        private string m_TRANSACTIONID;
        
        private decimal m_ENTERPRISEID;
        
        private string m_ISVOLUNTEER;
        
        private System.DateTime m_DEALTIME = DateTime.MinValue;
        
        private string m_ISROUTER;
        
        private string m_HASTRACED;
        
        private string m_ISSERVICE;
        
        private string m_REMARK;
        
        private string m_ISBACK;
        
        private decimal m_ENTERTYPE;
        
        private string m_OWNMONEY;
        
        private string m_ISASSISTANCER;
        
        private decimal m_ASSISTANCERID;
        
        private decimal m_HAVEMONEY;
        
        private decimal m_SERVICETIME;
        
        /// <summary>构造函数</summary>
        public T_SERVICEENTERPRISEEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性TRANSACTORID </summary>
        public string TRANSACTORID
        {
            get
            {
                return this.m_TRANSACTORID;
            }
            set
            {
                this.m_TRANSACTORID = value;
            }
        }
        
        /// <summary>属性TRANSACTIONID </summary>
        public string TRANSACTIONID
        {
            get
            {
                return this.m_TRANSACTIONID;
            }
            set
            {
                this.m_TRANSACTIONID = value;
            }
        }
        
        /// <summary>属性ENTERPRISEID </summary>
        public decimal ENTERPRISEID
        {
            get
            {
                return this.m_ENTERPRISEID;
            }
            set
            {
                this.m_ENTERPRISEID = value;
            }
        }
        
        /// <summary>属性ISVOLUNTEER </summary>
        public string ISVOLUNTEER
        {
            get
            {
                return this.m_ISVOLUNTEER;
            }
            set
            {
                this.m_ISVOLUNTEER = value;
            }
        }
        
        /// <summary>属性DEALTIME </summary>
        public System.DateTime DEALTIME
        {
            get
            {
                return this.m_DEALTIME;
            }
            set
            {
                this.m_DEALTIME = value;
            }
        }
        
        /// <summary>属性ISROUTER </summary>
        public string ISROUTER
        {
            get
            {
                return this.m_ISROUTER;
            }
            set
            {
                this.m_ISROUTER = value;
            }
        }
        
        /// <summary>属性HASTRACED </summary>
        public string HASTRACED
        {
            get
            {
                return this.m_HASTRACED;
            }
            set
            {
                this.m_HASTRACED = value;
            }
        }
        
        /// <summary>属性ISSERVICE </summary>
        public string ISSERVICE
        {
            get
            {
                return this.m_ISSERVICE;
            }
            set
            {
                this.m_ISSERVICE = value;
            }
        }
        
        /// <summary>属性REMARK </summary>
        public string REMARK
        {
            get
            {
                return this.m_REMARK;
            }
            set
            {
                this.m_REMARK = value;
            }
        }
        
        /// <summary>属性ISBACK </summary>
        public string ISBACK
        {
            get
            {
                return this.m_ISBACK;
            }
            set
            {
                this.m_ISBACK = value;
            }
        }
        
        /// <summary>属性ENTERTYPE </summary>
        public decimal ENTERTYPE
        {
            get
            {
                return this.m_ENTERTYPE;
            }
            set
            {
                this.m_ENTERTYPE = value;
            }
        }
        
        /// <summary>属性OWNMONEY </summary>
        public string OWNMONEY
        {
            get
            {
                return this.m_OWNMONEY;
            }
            set
            {
                this.m_OWNMONEY = value;
            }
        }
        
        /// <summary>属性ISASSISTANCER </summary>
        public string ISASSISTANCER
        {
            get
            {
                return this.m_ISASSISTANCER;
            }
            set
            {
                this.m_ISASSISTANCER = value;
            }
        }
        
        /// <summary>属性ASSISTANCERID </summary>
        public decimal ASSISTANCERID
        {
            get
            {
                return this.m_ASSISTANCERID;
            }
            set
            {
                this.m_ASSISTANCERID = value;
            }
        }
        
        /// <summary>属性HAVEMONEY </summary>
        public decimal HAVEMONEY
        {
            get
            {
                return this.m_HAVEMONEY;
            }
            set
            {
                this.m_HAVEMONEY = value;
            }
        }
        
        /// <summary>属性SERVICETIME </summary>
        public decimal SERVICETIME
        {
            get
            {
                return this.m_SERVICETIME;
            }
            set
            {
                this.m_SERVICETIME = value;
            }
        }
    }
    
    /// T_SERVICEENTERPRISEEntity执行类
    public abstract class T_SERVICEENTERPRISEEntityAction
    {
        
        public T_SERVICEENTERPRISEEntityAction()
        {
        }
        
        public static void Save(T_SERVICEENTERPRISEEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_SERVICEENTERPRISEEntity RetrieveAT_SERVICEENTERPRISEEntity(decimal ID)
        {
            T_SERVICEENTERPRISEEntity obj=new T_SERVICEENTERPRISEEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_SERVICEENTERPRISEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SERVICEENTERPRISEEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_SERVICEENTERPRISEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SERVICEENTERPRISEEntity));
            return rc.AsDataTable();
        }
    }
}
