//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/19 13:22:15
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_SERVICETRACINGEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>TRANSACTIONID</summary>
        public const string @__TRANSACTIONID = "TRANSACTIONID";
        
        /// <summary>ISROUTER</summary>
        public const string @__ISROUTER = "ISROUTER";
        
        /// <summary>ENTERPRISEID</summary>
        public const string @__ENTERPRISEID = "ENTERPRISEID";
        
        /// <summary>TRANSACTORID</summary>
        public const string @__TRANSACTORID = "TRANSACTORID";
        
        /// <summary>TRACETIME</summary>
        public const string @__TRACETIME = "TRACETIME";
        
        /// <summary>TRACETYPE</summary>
        public const string @__TRACETYPE = "TRACETYPE";
        
        /// <summary>TRACERESULT</summary>
        public const string @__TRACERESULT = "TRACERESULT";
        
        /// <summary>TRACEREMARK</summary>
        public const string @__TRACEREMARK = "TRACEREMARK";
        
        /// <summary>SERVTIME</summary>
        public const string @__SERVTIME = "SERVTIME";
        
        /// <summary>SERVSCORE</summary>
        public const string @__SERVSCORE = "SERVSCORE";
        
        /// <summary>ISSERVED</summary>
        public const string @__ISSERVED = "ISSERVED";
        
        /// <summary>ISTHREE</summary>
        public const string @__ISTHREE = "ISTHREE";
        
        /// <summary>SERVTIMED</summary>
        public const string @__SERVTIMED = "SERVTIMED";
        
        /// <summary>SERVQUALITY</summary>
        public const string @__SERVQUALITY = "SERVQUALITY";
        
        /// <summary>SERVPRICE</summary>
        public const string @__SERVPRICE = "SERVPRICE";
        
        /// <summary>SERVSATISFACTION</summary>
        public const string @__SERVSATISFACTION = "SERVSATISFACTION";
        
        /// <summary>SERVREMARK</summary>
        public const string @__SERVREMARK = "SERVREMARK";
        
        /// <summary>STATUS</summary>
        public const string @__STATUS = "STATUS";
        
        private decimal m_ID;
        
        private string m_TRANSACTIONID;
        
        private string m_ISROUTER;
        
        private decimal m_ENTERPRISEID;
        
        private string m_TRANSACTORID;
        
        private System.DateTime m_TRACETIME = DateTime.MinValue;
        
        private string m_TRACETYPE;
        
        private string m_TRACERESULT;
        
        private string m_TRACEREMARK;
        
        private System.DateTime m_SERVTIME = DateTime.MinValue;
        
        private string m_SERVSCORE;
        
        private string m_ISSERVED;
        
        private string m_ISTHREE;
        
        private string m_SERVTIMED;
        
        private string m_SERVQUALITY;
        
        private string m_SERVPRICE;
        
        private string m_SERVSATISFACTION;
        
        private string m_SERVREMARK;
        
        private decimal m_STATUS;
        
        /// <summary>构造函数</summary>
        public T_SERVICETRACINGEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性TRANSACTIONID </summary>
        public string TRANSACTIONID
        {
            get
            {
                return this.m_TRANSACTIONID;
            }
            set
            {
                this.m_TRANSACTIONID = value;
            }
        }
        
        /// <summary>属性ISROUTER </summary>
        public string ISROUTER
        {
            get
            {
                return this.m_ISROUTER;
            }
            set
            {
                this.m_ISROUTER = value;
            }
        }
        
        /// <summary>属性ENTERPRISEID </summary>
        public decimal ENTERPRISEID
        {
            get
            {
                return this.m_ENTERPRISEID;
            }
            set
            {
                this.m_ENTERPRISEID = value;
            }
        }
        
        /// <summary>属性TRANSACTORID </summary>
        public string TRANSACTORID
        {
            get
            {
                return this.m_TRANSACTORID;
            }
            set
            {
                this.m_TRANSACTORID = value;
            }
        }
        
        /// <summary>属性TRACETIME </summary>
        public System.DateTime TRACETIME
        {
            get
            {
                return this.m_TRACETIME;
            }
            set
            {
                this.m_TRACETIME = value;
            }
        }
        
        /// <summary>属性TRACETYPE </summary>
        public string TRACETYPE
        {
            get
            {
                return this.m_TRACETYPE;
            }
            set
            {
                this.m_TRACETYPE = value;
            }
        }
        
        /// <summary>属性TRACERESULT </summary>
        public string TRACERESULT
        {
            get
            {
                return this.m_TRACERESULT;
            }
            set
            {
                this.m_TRACERESULT = value;
            }
        }
        
        /// <summary>属性TRACEREMARK </summary>
        public string TRACEREMARK
        {
            get
            {
                return this.m_TRACEREMARK;
            }
            set
            {
                this.m_TRACEREMARK = value;
            }
        }
        
        /// <summary>属性SERVTIME </summary>
        public System.DateTime SERVTIME
        {
            get
            {
                return this.m_SERVTIME;
            }
            set
            {
                this.m_SERVTIME = value;
            }
        }
        
        /// <summary>属性SERVSCORE </summary>
        public string SERVSCORE
        {
            get
            {
                return this.m_SERVSCORE;
            }
            set
            {
                this.m_SERVSCORE = value;
            }
        }
        
        /// <summary>属性ISSERVED </summary>
        public string ISSERVED
        {
            get
            {
                return this.m_ISSERVED;
            }
            set
            {
                this.m_ISSERVED = value;
            }
        }
        
        /// <summary>属性ISTHREE </summary>
        public string ISTHREE
        {
            get
            {
                return this.m_ISTHREE;
            }
            set
            {
                this.m_ISTHREE = value;
            }
        }
        
        /// <summary>属性SERVTIMED </summary>
        public string SERVTIMED
        {
            get
            {
                return this.m_SERVTIMED;
            }
            set
            {
                this.m_SERVTIMED = value;
            }
        }
        
        /// <summary>属性SERVQUALITY </summary>
        public string SERVQUALITY
        {
            get
            {
                return this.m_SERVQUALITY;
            }
            set
            {
                this.m_SERVQUALITY = value;
            }
        }
        
        /// <summary>属性SERVPRICE </summary>
        public string SERVPRICE
        {
            get
            {
                return this.m_SERVPRICE;
            }
            set
            {
                this.m_SERVPRICE = value;
            }
        }
        
        /// <summary>属性SERVSATISFACTION </summary>
        public string SERVSATISFACTION
        {
            get
            {
                return this.m_SERVSATISFACTION;
            }
            set
            {
                this.m_SERVSATISFACTION = value;
            }
        }
        
        /// <summary>属性SERVREMARK </summary>
        public string SERVREMARK
        {
            get
            {
                return this.m_SERVREMARK;
            }
            set
            {
                this.m_SERVREMARK = value;
            }
        }
        
        /// <summary>属性STATUS </summary>
        public decimal STATUS
        {
            get
            {
                return this.m_STATUS;
            }
            set
            {
                this.m_STATUS = value;
            }
        }
    }
    
    /// T_SERVICETRACINGEntity执行类
    public abstract class T_SERVICETRACINGEntityAction
    {
        
        public T_SERVICETRACINGEntityAction()
        {
        }
        
        public static void Save(T_SERVICETRACINGEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_SERVICETRACINGEntity RetrieveAT_SERVICETRACINGEntity(decimal ID)
        {
            T_SERVICETRACINGEntity obj=new T_SERVICETRACINGEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_SERVICETRACINGEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SERVICETRACINGEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_SERVICETRACINGEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SERVICETRACINGEntity));
            return rc.AsDataTable();
        }
    }
}
