//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/24 19:00:07
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_SURVEYANSWEREntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>SAMESURVEYID</summary>
        public const string @__SAMESURVEYID = "SAMESURVEYID";
        
        /// <summary>QUESTIONID</summary>
        public const string @__QUESTIONID = "QUESTIONID";
        
        /// <summary>KEYWORD</summary>
        public const string @__KEYWORD = "KEYWORD";
        
        /// <summary>REMARK</summary>
        public const string @__REMARK = "REMARK";
        
        private decimal m_ID;
        
        private string m_SAMESURVEYID;
        
        private decimal m_QUESTIONID;
        
        private string m_KEYWORD;
        
        private string m_REMARK;
        
        /// <summary>构造函数</summary>
        public T_SURVEYANSWEREntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性SAMESURVEYID </summary>
        public string SAMESURVEYID
        {
            get
            {
                return this.m_SAMESURVEYID;
            }
            set
            {
                this.m_SAMESURVEYID = value;
            }
        }
        
        /// <summary>属性QUESTIONID </summary>
        public decimal QUESTIONID
        {
            get
            {
                return this.m_QUESTIONID;
            }
            set
            {
                this.m_QUESTIONID = value;
            }
        }
        
        /// <summary>属性KEYWORD </summary>
        public string KEYWORD
        {
            get
            {
                return this.m_KEYWORD;
            }
            set
            {
                this.m_KEYWORD = value;
            }
        }
        
        /// <summary>属性REMARK </summary>
        public string REMARK
        {
            get
            {
                return this.m_REMARK;
            }
            set
            {
                this.m_REMARK = value;
            }
        }
    }
    
    /// T_SURVEYANSWEREntity执行类
    public abstract class T_SURVEYANSWEREntityAction
    {
        
        private T_SURVEYANSWEREntityAction()
        {
        }
        
        public static void Save(T_SURVEYANSWEREntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_SURVEYANSWEREntity RetrieveAT_SURVEYANSWEREntity(decimal ID)
        {
            T_SURVEYANSWEREntity obj=new T_SURVEYANSWEREntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_SURVEYANSWEREntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SURVEYANSWEREntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_SURVEYANSWEREntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SURVEYANSWEREntity));
            return rc.AsDataTable();
        }
    }
}
