//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/24 19:00:07
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_SURVEYREPLYEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>SURVEYID</summary>
        public const string @__SURVEYID = "SURVEYID";
        
        /// <summary>SAMESURVEYID</summary>
        public const string @__SAMESURVEYID = "SAMESURVEYID";
        
        /// <summary>MEMBERID</summary>
        public const string @__MEMBERID = "MEMBERID";
        
        /// <summary>IPADDRESS</summary>
        public const string @__IPADDRESS = "IPADDRESS";
        
        /// <summary>REPLYTIME</summary>
        public const string @__REPLYTIME = "REPLYTIME";
        
        private decimal m_ID;
        
        private decimal m_SURVEYID;
        
        private string m_SAMESURVEYID;
        
        private decimal m_MEMBERID;
        
        private string m_IPADDRESS;
        
        private System.DateTime m_REPLYTIME = DateTime.MinValue;
        
        /// <summary>构造函数</summary>
        public T_SURVEYREPLYEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性SURVEYID </summary>
        public decimal SURVEYID
        {
            get
            {
                return this.m_SURVEYID;
            }
            set
            {
                this.m_SURVEYID = value;
            }
        }
        
        /// <summary>属性SAMESURVEYID </summary>
        public string SAMESURVEYID
        {
            get
            {
                return this.m_SAMESURVEYID;
            }
            set
            {
                this.m_SAMESURVEYID = value;
            }
        }
        
        /// <summary>属性MEMBERID </summary>
        public decimal MEMBERID
        {
            get
            {
                return this.m_MEMBERID;
            }
            set
            {
                this.m_MEMBERID = value;
            }
        }
        
        /// <summary>属性IPADDRESS </summary>
        public string IPADDRESS
        {
            get
            {
                return this.m_IPADDRESS;
            }
            set
            {
                this.m_IPADDRESS = value;
            }
        }
        
        /// <summary>属性REPLYTIME </summary>
        public System.DateTime REPLYTIME
        {
            get
            {
                return this.m_REPLYTIME;
            }
            set
            {
                this.m_REPLYTIME = value;
            }
        }
    }
    
    /// T_SURVEYREPLYEntity执行类
    public abstract class T_SURVEYREPLYEntityAction
    {
        
        private T_SURVEYREPLYEntityAction()
        {
        }
        
        public static void Save(T_SURVEYREPLYEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_SURVEYREPLYEntity RetrieveAT_SURVEYREPLYEntity(decimal ID)
        {
            T_SURVEYREPLYEntity obj=new T_SURVEYREPLYEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_SURVEYREPLYEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SURVEYREPLYEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_SURVEYREPLYEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SURVEYREPLYEntity));
            return rc.AsDataTable();
        }
    }
}
