//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/24 13:25:20
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_SURVEYQUESTIONEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>SURVEYID</summary>
        public const string @__SURVEYID = "SURVEYID";
        
        /// <summary>QUESTIONID</summary>
        public const string @__QUESTIONID = "QUESTIONID";
        
        /// <summary>TYPE</summary>
        public const string @__TYPE = "TYPE";
        
        /// <summary>TITLE</summary>
        public const string @__TITLE = "TITLE";
        
        /// <summary>ANSWER</summary>
        public const string @__ANSWER = "ANSWER";
        
        /// <summary>ISTEXT</summary>
        public const string @__ISTEXT = "ISTEXT";
        
        private decimal m_ID;
        
        private decimal m_SURVEYID;
        
        private decimal m_QUESTIONID;
        
        private string m_TYPE;
        
        private string m_TITLE;
        
        private string m_ANSWER;
        
        private string m_ISTEXT;
        
        /// <summary>构造函数</summary>
        public T_SURVEYQUESTIONEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性SURVEYID </summary>
        public decimal SURVEYID
        {
            get
            {
                return this.m_SURVEYID;
            }
            set
            {
                this.m_SURVEYID = value;
            }
        }
        
        /// <summary>属性QUESTIONID </summary>
        public decimal QUESTIONID
        {
            get
            {
                return this.m_QUESTIONID;
            }
            set
            {
                this.m_QUESTIONID = value;
            }
        }
        
        /// <summary>属性TYPE </summary>
        public string TYPE
        {
            get
            {
                return this.m_TYPE;
            }
            set
            {
                this.m_TYPE = value;
            }
        }
        
        /// <summary>属性TITLE </summary>
        public string TITLE
        {
            get
            {
                return this.m_TITLE;
            }
            set
            {
                this.m_TITLE = value;
            }
        }
        
        /// <summary>属性ANSWER </summary>
        public string ANSWER
        {
            get
            {
                return this.m_ANSWER;
            }
            set
            {
                this.m_ANSWER = value;
            }
        }
        
        /// <summary>属性ISTEXT </summary>
        public string ISTEXT
        {
            get
            {
                return this.m_ISTEXT;
            }
            set
            {
                this.m_ISTEXT = value;
            }
        }
    }
    
    /// T_SURVEYQUESTIONEntity执行类
    public abstract class T_SURVEYQUESTIONEntityAction
    {
        
        private T_SURVEYQUESTIONEntityAction()
        {
        }
        
        public static void Save(T_SURVEYQUESTIONEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_SURVEYQUESTIONEntity RetrieveAT_SURVEYQUESTIONEntity(decimal ID)
        {
            T_SURVEYQUESTIONEntity obj=new T_SURVEYQUESTIONEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_SURVEYQUESTIONEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SURVEYQUESTIONEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_SURVEYQUESTIONEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_SURVEYQUESTIONEntity));
            return rc.AsDataTable();
        }
    }
}
