//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/19 13:22:15
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_TRANSACTIONINFOEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>TRANSACTIONID</summary>
        public const string @__TRANSACTIONID = "TRANSACTIONID";
        
        /// <summary>QUERYTYPE</summary>
        public const string @__QUERYTYPE = "QUERYTYPE";
        
        /// <summary>CALLTEL</summary>
        public const string @__CALLTEL = "CALLTEL";
        
        /// <summary>NAME</summary>
        public const string @__NAME = "NAME";
        
        /// <summary>SEX</summary>
        public const string @__SEX = "SEX";
        
        /// <summary>WORKPLACE</summary>
        public const string @__WORKPLACE = "WORKPLACE";
        
        /// <summary>ADDRESS</summary>
        public const string @__ADDRESS = "ADDRESS";
        
        /// <summary>OTHERLINK</summary>
        public const string @__OTHERLINK = "OTHERLINK";
        
        /// <summary>REMARK</summary>
        public const string @__REMARK = "REMARK";
        
        /// <summary>CUSTOMERTYPE</summary>
        public const string @__CUSTOMERTYPE = "CUSTOMERTYPE";
        
        /// <summary>LONGUTIDE</summary>
        public const string @__LONGUTIDE = "LONGUTIDE";
        
        /// <summary>LATITUDE</summary>
        public const string @__LATITUDE = "LATITUDE";
        
        /// <summary>AREACODE</summary>
        public const string @__AREACODE = "AREACODE";
        
        private decimal m_ID;
        
        private string m_TRANSACTIONID;
        
        private string m_QUERYTYPE;
        
        private string m_CALLTEL;
        
        private string m_NAME;
        
        private string m_SEX;
        
        private string m_WORKPLACE;
        
        private string m_ADDRESS;
        
        private string m_OTHERLINK;
        
        private string m_REMARK;
        
        private string m_CUSTOMERTYPE;
        
        private string m_LONGUTIDE;
        
        private string m_LATITUDE;
        
        private string m_AREACODE;
        
        /// <summary>构造函数</summary>
        public T_TRANSACTIONINFOEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性TRANSACTIONID </summary>
        public string TRANSACTIONID
        {
            get
            {
                return this.m_TRANSACTIONID;
            }
            set
            {
                this.m_TRANSACTIONID = value;
            }
        }
        
        /// <summary>属性QUERYTYPE </summary>
        public string QUERYTYPE
        {
            get
            {
                return this.m_QUERYTYPE;
            }
            set
            {
                this.m_QUERYTYPE = value;
            }
        }
        
        /// <summary>属性CALLTEL </summary>
        public string CALLTEL
        {
            get
            {
                return this.m_CALLTEL;
            }
            set
            {
                this.m_CALLTEL = value;
            }
        }
        
        /// <summary>属性NAME </summary>
        public string NAME
        {
            get
            {
                return this.m_NAME;
            }
            set
            {
                this.m_NAME = value;
            }
        }
        
        /// <summary>属性SEX </summary>
        public string SEX
        {
            get
            {
                return this.m_SEX;
            }
            set
            {
                this.m_SEX = value;
            }
        }
        
        /// <summary>属性WORKPLACE </summary>
        public string WORKPLACE
        {
            get
            {
                return this.m_WORKPLACE;
            }
            set
            {
                this.m_WORKPLACE = value;
            }
        }
        
        /// <summary>属性ADDRESS </summary>
        public string ADDRESS
        {
            get
            {
                return this.m_ADDRESS;
            }
            set
            {
                this.m_ADDRESS = value;
            }
        }
        
        /// <summary>属性OTHERLINK </summary>
        public string OTHERLINK
        {
            get
            {
                return this.m_OTHERLINK;
            }
            set
            {
                this.m_OTHERLINK = value;
            }
        }
        
        /// <summary>属性REMARK </summary>
        public string REMARK
        {
            get
            {
                return this.m_REMARK;
            }
            set
            {
                this.m_REMARK = value;
            }
        }
        
        /// <summary>属性CUSTOMERTYPE </summary>
        public string CUSTOMERTYPE
        {
            get
            {
                return this.m_CUSTOMERTYPE;
            }
            set
            {
                this.m_CUSTOMERTYPE = value;
            }
        }
        
        /// <summary>属性LONGUTIDE </summary>
        public string LONGUTIDE
        {
            get
            {
                return this.m_LONGUTIDE;
            }
            set
            {
                this.m_LONGUTIDE = value;
            }
        }
        
        /// <summary>属性LATITUDE </summary>
        public string LATITUDE
        {
            get
            {
                return this.m_LATITUDE;
            }
            set
            {
                this.m_LATITUDE = value;
            }
        }
        
        /// <summary>属性AREACODE </summary>
        public string AREACODE
        {
            get
            {
                return this.m_AREACODE;
            }
            set
            {
                this.m_AREACODE = value;
            }
        }
    }
    
    /// T_TRANSACTIONINFOEntity执行类
    public abstract class T_TRANSACTIONINFOEntityAction
    {
        
        public T_TRANSACTIONINFOEntityAction()
        {
        }
        
        public static void Save(T_TRANSACTIONINFOEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_TRANSACTIONINFOEntity RetrieveAT_TRANSACTIONINFOEntity(decimal ID)
        {
            T_TRANSACTIONINFOEntity obj=new T_TRANSACTIONINFOEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_TRANSACTIONINFOEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_TRANSACTIONINFOEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_TRANSACTIONINFOEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_TRANSACTIONINFOEntity));
            return rc.AsDataTable();
        }
    }
}
