//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/11 13:36:27
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_WEBMANAGEROLEEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>USERNAME</summary>
        public const string @__USERNAME = "USERNAME";
        
        /// <summary>NODEID</summary>
        public const string @__NODEID = "NODEID";
        
        private decimal m_ID;
        
        private string m_USERNAME;
        
        private decimal m_NODEID;
        
        /// <summary>构造函数</summary>
        public T_WEBMANAGEROLEEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性USERNAME </summary>
        public string USERNAME
        {
            get
            {
                return this.m_USERNAME;
            }
            set
            {
                this.m_USERNAME = value;
            }
        }
        
        /// <summary>属性NODEID </summary>
        public decimal NODEID
        {
            get
            {
                return this.m_NODEID;
            }
            set
            {
                this.m_NODEID = value;
            }
        }
    }
    
    /// T_WEBMANAGEROLEEntity执行类
    public abstract class T_WEBMANAGEROLEEntityAction
    {
        
        private T_WEBMANAGEROLEEntityAction()
        {
        }
        
        public static void Save(T_WEBMANAGEROLEEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_WEBMANAGEROLEEntity RetrieveAT_WEBMANAGEROLEEntity(decimal ID)
        {
            T_WEBMANAGEROLEEntity obj=new T_WEBMANAGEROLEEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_WEBMANAGEROLEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_WEBMANAGEROLEEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_WEBMANAGEROLEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_WEBMANAGEROLEEntity));
            return rc.AsDataTable();
        }
    }
}
