//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------
// 
//             Powered By： SR3.1(SmartRobot For SmartPersistenceLayer 3.1) 听棠
//             Created By： Administrator
//             Created Time： 2016/5/11 13:36:27
// 
// -------------------------------------------------------------
namespace Web.BusinessEntity
{
    using System;
    using System.Collections;
    using System.Data;
    using PersistenceLayer;
    
    
    /// <summary>该类的摘要说明</summary>
    [Serializable()]
    public class T_WEBMANAGEEntity : EntityObject
    {
        
        /// <summary>ID</summary>
        public const string @__ID = "ID";
        
        /// <summary>USERNAME</summary>
        public const string @__USERNAME = "USERNAME";
        
        /// <summary>PASSWORD</summary>
        public const string @__PASSWORD = "PASSWORD";
        
        /// <summary>TRUENAME</summary>
        public const string @__TRUENAME = "TRUENAME";
        
        /// <summary>CREATETIME</summary>
        public const string @__CREATETIME = "CREATETIME";
        
        /// <summary>LASTLOGINIP</summary>
        public const string @__LASTLOGINIP = "LASTLOGINIP";
        
        /// <summary>LASTLOGINTIME</summary>
        public const string @__LASTLOGINTIME = "LASTLOGINTIME";
        
        /// <summary>TELEPHONE</summary>
        public const string @__TELEPHONE = "TELEPHONE";
        
        /// <summary>DEPT</summary>
        public const string @__DEPT = "DEPT";
        
        /// <summary>STATUS</summary>
        public const string @__STATUS = "STATUS";
        
        private decimal m_ID;
        
        private string m_USERNAME;
        
        private string m_PASSWORD;
        
        private string m_TRUENAME;
        
        private System.DateTime m_CREATETIME = DateTime.MinValue;
        
        private string m_LASTLOGINIP;
        
        private System.DateTime m_LASTLOGINTIME = DateTime.MinValue;
        
        private string m_TELEPHONE;
        
        private string m_DEPT;
        
        private decimal m_STATUS;
        
        /// <summary>构造函数</summary>
        public T_WEBMANAGEEntity()
        {
        }
        
        /// <summary>属性ID </summary>
        public decimal ID
        {
            get
            {
                return this.m_ID;
            }
            set
            {
                this.m_ID = value;
            }
        }
        
        /// <summary>属性USERNAME </summary>
        public string USERNAME
        {
            get
            {
                return this.m_USERNAME;
            }
            set
            {
                this.m_USERNAME = value;
            }
        }
        
        /// <summary>属性PASSWORD </summary>
        public string PASSWORD
        {
            get
            {
                return this.m_PASSWORD;
            }
            set
            {
                this.m_PASSWORD = value;
            }
        }
        
        /// <summary>属性TRUENAME </summary>
        public string TRUENAME
        {
            get
            {
                return this.m_TRUENAME;
            }
            set
            {
                this.m_TRUENAME = value;
            }
        }
        
        /// <summary>属性CREATETIME </summary>
        public System.DateTime CREATETIME
        {
            get
            {
                return this.m_CREATETIME;
            }
            set
            {
                this.m_CREATETIME = value;
            }
        }
        
        /// <summary>属性LASTLOGINIP </summary>
        public string LASTLOGINIP
        {
            get
            {
                return this.m_LASTLOGINIP;
            }
            set
            {
                this.m_LASTLOGINIP = value;
            }
        }
        
        /// <summary>属性LASTLOGINTIME </summary>
        public System.DateTime LASTLOGINTIME
        {
            get
            {
                return this.m_LASTLOGINTIME;
            }
            set
            {
                this.m_LASTLOGINTIME = value;
            }
        }
        
        /// <summary>属性TELEPHONE </summary>
        public string TELEPHONE
        {
            get
            {
                return this.m_TELEPHONE;
            }
            set
            {
                this.m_TELEPHONE = value;
            }
        }
        
        /// <summary>属性DEPT </summary>
        public string DEPT
        {
            get
            {
                return this.m_DEPT;
            }
            set
            {
                this.m_DEPT = value;
            }
        }
        
        /// <summary>属性STATUS </summary>
        public decimal STATUS
        {
            get
            {
                return this.m_STATUS;
            }
            set
            {
                this.m_STATUS = value;
            }
        }
    }
    
    /// T_WEBMANAGEEntity执行类
    public abstract class T_WEBMANAGEEntityAction
    {
        
        private T_WEBMANAGEEntityAction()
        {
        }
        
        public static void Save(T_WEBMANAGEEntity obj)
        {
            if (obj!=null)
            {
                obj.Save();
            }
        }
        
        /// <summary>根据主键获取一个实体</summary>
        public static T_WEBMANAGEEntity RetrieveAT_WEBMANAGEEntity(decimal ID)
        {
            T_WEBMANAGEEntity obj=new T_WEBMANAGEEntity();
            obj.ID=ID;
            obj.Retrieve();
            if (obj.IsPersistent)
            {
                return obj;
            }
            else
            {
                return null;
            }
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static EntityContainer RetrieveT_WEBMANAGEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_WEBMANAGEEntity));
            return rc.AsEntityContainer();
        }
        
        /// <summary>获取所有实体(EntityContainer)</summary>
        public static DataTable GetT_WEBMANAGEEntity()
        {
            RetrieveCriteria rc=new RetrieveCriteria(typeof(T_WEBMANAGEEntity));
            return rc.AsDataTable();
        }
    }
}
